#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "com_definitions.h"
#include "cli.h"
#include "init.h"
#include "logger.h"
#include "srp.h"
#include "all_comps.h"
#include "common_macro.h"
#include<time.h> 

int program_rx_ip_registers();
int program_rx_glue_registers();
int program_cmn_csr_registers();
int program_nsip_hbi_map_registers();
int program_bfn_registers();
int program_enable_registers();
void delay(unsigned int mseconds);
uint16_t core_number;
uint16_t i,j,k;

int main(int argc, char **argv)
{

	uint32_t read_value;
	extern void * srp;
	//uint16_t i,j,k;
	//uint16_t core_number;
	uint32_t error = 0;
	uint32_t write_status = 0;

	uint32_t tx_gb_empty = 0;
	uint32_t tx_gb_full = 0;
	uint32_t rx_gb_empty = 0;
	uint32_t rx_gb_full = 0;

	init();

	// function calls - Reg seq usecase 0a
	program_rx_ip_registers();
	program_cmn_csr_registers();
	program_rx_glue_registers();
	printf("Giving delay of 10 milli seconds \n");
	delay(10);
	tx_gb_empty = read_reg(SRP_BLOCK_JESD_XIP_TX, 0, 0x000003E8, "JL_N_TX_GB_EMPTY_REG");
	tx_gb_full = read_reg(SRP_BLOCK_JESD_XIP_TX, 0, 0x000003EC, "JL_N_TX_GB_FULL_REG");
	rx_gb_empty = read_reg(SRP_BLOCK_JESD_XIP_RX, 0, 0x000003E8, "JL_N_RX_GB_EMPTY_REG");
	rx_gb_full = read_reg(SRP_BLOCK_JESD_XIP_RX, 0, 0x000003EC, "JL_N_RX_GB_FULL_REG");
	printf(" Before jesd enable value for JL_N_TX_GB_EMPTY_REG --------is 0x%x \n", tx_gb_empty);
	printf(" Before jesd enable value for JL_N_TX_GB_FULL_REG ---------is 0x%x \n", tx_gb_full);
	printf(" Before jesd enable value for JL_N_RX_GB_EMPTY_REG --------is 0x%x \n", rx_gb_empty);
	printf(" Before jesd enable value for JL_N_RX_GB_FULL_REG ---------is 0x%x \n", rx_gb_full);

	program_enable_registers();

}

void delay(unsigned int milliseconds){

    clock_t start = clock();

    while((clock() - start) * 1000 / CLOCKS_PER_SEC < milliseconds);
}

// JESD CMN CSR reg
int program_cmn_csr_registers()
{
	printf("JESD CMN CSR CONFIG : program_cmn_csr_registers \n");
	for (core_number=0; core_number <= 1; core_number++)
	{
		write_read_expect(SRP_BLOCK_JESD_CMN_CSR, core_number,JESD_JESDABC_CMN_CSR_TX_CLK_CTRL,0x0000000a,0x0000000a,JESD_JESDABC_CMN_CSR_TX_CLK_CTRL_RD_MASK,JESD_JESDABC_CMN_CSR_TX_CLK_CTRL_WR_MASK,"JESD_JESDABC_CMN_CSR_TX_CLK_CTRL");
		write_read_expect(SRP_BLOCK_JESD_CMN_CSR, core_number,JESD_JESDABC_CMN_CSR_RX_CLK_CTRL,0x0000000a,0x0000000a,JESD_JESDABC_CMN_CSR_RX_CLK_CTRL_RD_MASK,JESD_JESDABC_CMN_CSR_RX_CLK_CTRL_WR_MASK,"JESD_JESDABC_CMN_CSR_RX_CLK_CTRL");
	}
}

// JESD RX reg
int program_rx_ip_registers()
{
	printf("JESD RX IP CONFIG : program_rx_ip_registers \n");
	for (core_number=0; core_number <= 1; core_number++)
	{
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_SUBCLASS_REG,0x00000001,0x00000001,JESD_XIP_RX_JL_SUBCLASS_REG_RD_MASK,JESD_XIP_RX_JL_SUBCLASS_REG_WR_MASK,"JESD_XIP_RX_JL_SUBCLASS_REG");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_FEC_ENB_REG,0x00000000,0x00000000,JESD_XIP_RX_JL_FEC_ENB_REG_RD_MASK,JESD_XIP_RX_JL_FEC_ENB_REG_WR_MASK,"JESD_XIP_RX_JL_FEC_ENB_REG");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_CRC3_EN_REG,0x00000000,0x00000000,JESD_XIP_RX_JL_CRC3_EN_REG_RD_MASK,JESD_XIP_RX_JL_CRC3_EN_REG_WR_MASK,"JESD_XIP_RX_JL_CRC3_EN_REG");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_CRC12_EN_REG,0x00000000,0x00000000,JESD_XIP_RX_JL_CRC12_EN_REG_RD_MASK,JESD_XIP_RX_JL_CRC12_EN_REG_WR_MASK,"JESD_XIP_RX_JL_CRC12_EN_REG");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_BIT_ORDER_REG,0x00000003,0x00000003,JESD_XIP_RX_JL_BIT_ORDER_REG_RD_MASK,JESD_XIP_RX_JL_BIT_ORDER_REG_WR_MASK,"JESD_XIP_RX_JL_BIT_ORDER_REG");
		
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_E_REG,0x00000000,0x00000000,JESD_XIP_RX_JL_E_REG_RD_MASK,JESD_XIP_RX_JL_E_REG_WR_MASK,"JESD_XIP_RX_JL_E_REG");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_CF_REG,0x00000000,0x00000000,JESD_XIP_RX_JL_CF_REG_RD_MASK,JESD_XIP_RX_JL_CF_REG_WR_MASK,"JESD_XIP_RX_JL_CF_REG");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_HD_REG,0x00000001,0x00000001,JESD_XIP_RX_JL_HD_REG_RD_MASK,JESD_XIP_RX_JL_HD_REG_WR_MASK,"JESD_XIP_RX_JL_HD_REG");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_CMD_ENB_REG,0x00000000,0x00000000,JESD_XIP_RX_JL_CMD_ENB_REG_RD_MASK,JESD_XIP_RX_JL_CMD_ENB_REG_WR_MASK,"JESD_XIP_RX_JL_CMD_ENB_REG");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_CLK_RATIO_REG,0x00000000,0x00000000,JESD_XIP_RX_JL_CLK_RATIO_REG_RD_MASK,JESD_XIP_RX_JL_CLK_RATIO_REG_WR_MASK,"JESD_XIP_RX_JL_CLK_RATIO_REG");
	
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_L_REG,0x00000001,0x00000001,JESD_XIP_RX_JL_L_REG_RD_MASK,JESD_XIP_RX_JL_L_REG_WR_MASK,"JESD_XIP_RX_JL_L_REG");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_M_REG,0x0000000f,0x0000000f,JESD_XIP_RX_JL_M_REG_RD_MASK,JESD_XIP_RX_JL_M_REG_WR_MASK,"JESD_XIP_RX_JL_M_REG");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_F_REG,0x0000000f,0x0000000f,JESD_XIP_RX_JL_F_REG_RD_MASK,JESD_XIP_RX_JL_F_REG_WR_MASK,"JESD_XIP_RX_JL_F_REG");
		
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_S_REG,0x00000000,0x00000000,JESD_XIP_RX_JL_S_REG_RD_MASK,JESD_XIP_RX_JL_S_REG_WR_MASK,"JESD_XIP_RX_JL_S_REG");
		
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_SONIF_REG,0x00000100,0x00000100,JESD_XIP_RX_JL_SONIF_REG_RD_MASK,JESD_XIP_RX_JL_SONIF_REG_WR_MASK,"JESD_XIP_RX_JL_SONIF_REG");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_N_REG,0x0000000f,0x0000000f,JESD_XIP_RX_JL_N_REG_RD_MASK,JESD_XIP_RX_JL_N_REG_WR_MASK,"JESD_XIP_RX_JL_N_REG");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_NTOTAL_REG,0x0000000f,0x0000000f,JESD_XIP_RX_JL_NTOTAL_REG_RD_MASK,JESD_XIP_RX_JL_NTOTAL_REG_WR_MASK,"JESD_XIP_RX_JL_NTOTAL_REG");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_CS_REG,0x00000000,0x00000000,JESD_XIP_RX_JL_CS_REG_RD_MASK,JESD_XIP_RX_JL_CS_REG_WR_MASK,"JESD_XIP_RX_JL_CS_REG");
		
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_TL_TESTMODE_REG,0x00000000,0x00000000,JESD_XIP_RX_JL_TL_TESTMODE_REG_RD_MASK,JESD_XIP_RX_JL_TL_TESTMODE_REG_WR_MASK,"JESD_XIP_RX_JL_TL_TESTMODE_REG");
		
		//is this SCR reg?
		//write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_SCR_EN_REG,0x00000001,0x00000001,JESD_XIP_RX_JL_SCR_EN_REG_RD_MASK,JESD_XIP_RX_JL_SCR_EN_REG_WR_MASK,"JESD_XIP_RX_JL_SCR_EN_REG");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_THRESH_SH_ERR_REG,0x00000010,0x00000010,JESD_XIP_RX_JL_THRESH_SH_ERR_REG_RD_MASK,JESD_XIP_RX_JL_THRESH_SH_ERR_REG_WR_MASK,"JESD_XIP_RX_JL_THRESH_SH_ERR_REG");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_THRESH_EMB_ERR_REG,0x00000008,0x00000008,JESD_XIP_RX_JL_THRESH_EMB_ERR_REG_RD_MASK,JESD_XIP_RX_JL_THRESH_EMB_ERR_REG_WR_MASK,"JESD_XIP_RX_JL_THRESH_EMB_ERR_REG");
	}
} 

//JESD RX glue reg
int program_rx_glue_registers()
{
	printf("JESD RX GLUE CONFIG : program_rx_glue_registers \n");
	for (core_number=0; core_number <= 1; core_number++)
	{
	
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0(0),0x00000000,0x00000000,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0_RD_MASK,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0_WR_MASK,"JESD_JESDABC_RX_GLUE_WR_MEM_TBL0");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0(0),0x00000000,0x00000000,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0_RD_MASK,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0_WR_MASK,"JESD_JESDABC_RX_GLUE_RD_MEM_TBL0");
		
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0(1),0x00000040,0x00000040,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0_RD_MASK,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0_WR_MASK,"JESD_JESDABC_RX_GLUE_WR_MEM_TBL0");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0(1),0x00000240,0x00000240,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0_RD_MASK,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0_WR_MASK,"JESD_JESDABC_RX_GLUE_RD_MEM_TBL0");
		
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0(2),0x00000080,0x00000080,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0_RD_MASK,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0_WR_MASK,"JESD_JESDABC_RX_GLUE_WR_MEM_TBL0");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0(2),0x00000480,0x00000480,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0_RD_MASK,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0_WR_MASK,"JESD_JESDABC_RX_GLUE_RD_MEM_TBL0");
		
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0(3),0x000000c0,0x000000c0,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0_RD_MASK,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0_WR_MASK,"JESD_JESDABC_RX_GLUE_WR_MEM_TBL0");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0(3),0x000006c0,0x000006c0,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0_RD_MASK,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0_WR_MASK,"JESD_JESDABC_RX_GLUE_RD_MEM_TBL0");
		
		
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0(4),0x00000100,0x00000100,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0_RD_MASK,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0_WR_MASK,"JESD_JESDABC_RX_GLUE_WR_MEM_TBL0");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0(4),0x00000900,0x00000900,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0_RD_MASK,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0_WR_MASK,"JESD_JESDABC_RX_GLUE_RD_MEM_TBL0");
		
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0(5),0x00000140,0x00000140,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0_RD_MASK,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0_WR_MASK,"JESD_JESDABC_RX_GLUE_WR_MEM_TBL0");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0(5),0x00000b40,0x00000b40,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0_RD_MASK,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0_WR_MASK,"JESD_JESDABC_RX_GLUE_RD_MEM_TBL0");
		
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0(6),0x00000180,0x00000180,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0_RD_MASK,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0_WR_MASK,"JESD_JESDABC_RX_GLUE_WR_MEM_TBL0");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0(6),0x00000d80,0x00000d80,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0_RD_MASK,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0_WR_MASK,"JESD_JESDABC_RX_GLUE_RD_MEM_TBL0");
		
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0(7),0x000001c0,0x000001c0,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0_RD_MASK,JESD_JESDABC_RX_GLUE_WR_MEM_TBL0_WR_MASK,"JESD_JESDABC_RX_GLUE_WR_MEM_TBL0");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0(7),0x00000fc0,0x00000fc0,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0_RD_MASK,JESD_JESDABC_RX_GLUE_RD_MEM_TBL0_WR_MASK,"JESD_JESDABC_RX_GLUE_RD_MEM_TBL0");
	
		
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_RX_GLUE_SONI,0x00000001,0x00000001,JESD_JESDABC_RX_GLUE_RX_GLUE_SONI_RD_MASK,JESD_JESDABC_RX_GLUE_RX_GLUE_SONI_WR_MASK,"JESD_JESDABC_RX_GLUE_RX_GLUE_SONI");
		//adding strm_cfg 0x000000e8
		
		//for (i=0; i <= 1; i++)
		
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_STRM_ID_EN(0),0x000001c8,0x000001c8,JESD_JESDABC_RX_GLUE_STRM_ID_EN_RD_MASK,JESD_JESDABC_RX_GLUE_STRM_ID_EN_WR_MASK,"JESD_JESDABC_RX_GLUE_STRM_ID_EN");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_MEM_STREAM_CFG(0),0x0000003f,0x0000003f,JESD_JESDABC_RX_GLUE_MEM_STREAM_CFG_RD_MASK,JESD_JESDABC_RX_GLUE_MEM_STREAM_CFG_WR_MASK,"JESD_JESDABC_RX_GLUE_MEM_STREAM_CFG");
		
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_STRM_ID_EN(1),0x00000000,0x00000000,JESD_JESDABC_RX_GLUE_STRM_ID_EN_RD_MASK,JESD_JESDABC_RX_GLUE_STRM_ID_EN_WR_MASK,"JESD_JESDABC_RX_GLUE_STRM_ID_EN");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX_GLUE, core_number,JESD_JESDABC_RX_GLUE_MEM_STREAM_CFG(1),0x00000000,0x00000000,JESD_JESDABC_RX_GLUE_MEM_STREAM_CFG_RD_MASK,JESD_JESDABC_RX_GLUE_MEM_STREAM_CFG_WR_MASK,"JESD_JESDABC_RX_GLUE_MEM_STREAM_CFG");
		
		
	}
}


// JESD enable reg
int program_enable_registers()
{
	printf("JESD ENABLE : program_enable_registers \n");
	for (core_number=0; core_number <= 1; core_number++)
	{
		write_read_expect(SRP_BLOCK_JESD_XIP_TX, core_number,JESD_XIP_TX_JL_JESD_ENABLE_REG,0x1,0x1,JESD_XIP_TX_JL_JESD_ENABLE_REG_RD_MASK,JESD_XIP_TX_JL_JESD_ENABLE_REG_WR_MASK,"JESD_XIP_TX_JL_JESD_ENABLE_REG");
		write_read_expect(SRP_BLOCK_JESD_XIP_RX, core_number,JESD_XIP_RX_JL_JESD_ENABLE_REG,0x1,0x1,JESD_XIP_RX_JL_JESD_ENABLE_REG_RD_MASK,JESD_XIP_RX_JL_JESD_ENABLE_REG_WR_MASK,"JESD_XIP_RX_JL_JESD_ENABLE_REG");
	}
}



