#ifndef _CMEM_SRAM_H_

// ******************************************************************************
// ------------------------------------------------------------------------------
//                               INTEL CONFIDENTIAL
// ------------------------------------------------------------------------------
//    Copyright (c) 2018 - 2024 Intel Corporation
//
//    This software and the related documents are Intel copyrighted materials,
//    and your use of them is governed by the express license under which they
//    were provided to you ("License").
//    Unless the License provides otherwise, you may not use, modify, copy, publish,
//    distribute, disclose or transmit this software or the related documents
//    without Intel's prior written permission.
//
//    This software and the related documents are provided as is, with no express or
//    implied warranties, other than those that are expressly stated in the License.
// ------------------------------------------------------------------------------
//
//    DO NOT EDIT THIS FILE !!!
//
//    This file has been automatically generated by OneSource
//
// ******************************************************************************

#ifndef __KERNEL__
#include <stdint.h>
#endif // __KERNEL__
// ******************************************* Base address macros

#define FB_ANT0_CMEM0_SRAM_BASE  ( 0x05000000 )
#define FB_ANT0_CMEM1_SRAM_BASE  ( 0x05040000 )
#define FB_ANT1_CMEM0_SRAM_BASE  ( 0x05080000 )
#define FB_ANT1_CMEM1_SRAM_BASE  ( 0x050c0000 )

// ******************************************* /Base address macros

#define CMEM_SRAM_MEM_CELL_ARR_SZ0 (4096)
// ******************************************* AddressSpace struct
typedef struct
{
    uint32_t MEM_CELL[4096][8]; /*< Address offset = 0x0 (256 bit) */
} cmem_sram_t;     // size: 0x0020

// AddressSpace struct pointer
//
#define FB_ANT0_CMEM0_SRAM  ((cmem_sram_t*) FB_ANT0_CMEM0_SRAM_BASE)
#define FB_ANT0_CMEM1_SRAM  ((cmem_sram_t*) FB_ANT0_CMEM1_SRAM_BASE)
#define FB_ANT1_CMEM0_SRAM  ((cmem_sram_t*) FB_ANT1_CMEM0_SRAM_BASE)
#define FB_ANT1_CMEM1_SRAM  ((cmem_sram_t*) FB_ANT1_CMEM1_SRAM_BASE)

// ******************************************* /Address Space

#endif      // _CMEM_SRAM_H_

