#ifndef _CMNANA_REFCKBUF_MSG_H_
#define _CMNANA_REFCKBUF_MSG_H_

// ******************************************************************************
// ------------------------------------------------------------------------------
//                               INTEL CONFIDENTIAL
// ------------------------------------------------------------------------------
//    Copyright (c) 2018 - 2024 Intel Corporation
//
//    This software and the related documents are Intel copyrighted materials,
//    and your use of them is governed by the express license under which they
//    were provided to you ("License").
//    Unless the License provides otherwise, you may not use, modify, copy, publish,
//    distribute, disclose or transmit this software or the related documents
//    without Intel's prior written permission.
//
//    This software and the related documents are provided as is, with no express or
//    implied warranties, other than those that are expressly stated in the License.
// ------------------------------------------------------------------------------
//
//    DO NOT EDIT THIS FILE !!!
//
//    This file has been automatically generated by OneSource
//
// ******************************************************************************

#ifndef __KERNEL__
#include <stdint.h>
#endif // __KERNEL__
// ******************************************* Base address macros

#define DLNK_JESD0_PHY_PMA0_CMNANA_REFCKBUF_BASE  ( 0x06020900 )
#define DLNK_JESD1_PHY_PMA0_CMNANA_REFCKBUF_BASE  ( 0x06820900 )
#define DLNK_JESD2_PHY_PMA0_CMNANA_REFCKBUF_BASE  ( 0x07020900 )
#define DLNK_JESD3_PHY_PMA0_CMNANA_REFCKBUF_BASE  ( 0x07820900 )

// ******************************************* /Base address macros


// ******************************************* Register offset macros

#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_OFFSET ( 0x00000000U )
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_OFFSET ( 0x00000004U )
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_OFFSET ( 0x00000008U )
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_OFFSET ( 0x0000000cU )
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_OFFSET ( 0x00000010U )
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_OFFSET ( 0x00000014U )
#define CMNANA_REFCKBUF_MSG_CMNREFCKBUF_SPARE0_OFFSET ( 0x00000018U )

// ******************************************* /Register offset macros


// ******************************************* AddressSpace macros
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_ADR(_BASE) (( ( _BASE ) + ( CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_OFFSET ) ))
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_ADR(_BASE) (( ( _BASE ) + ( CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_OFFSET ) ))
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_ADR(_BASE) (( ( _BASE ) + ( CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_OFFSET ) ))
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_ADR(_BASE) (( ( _BASE ) + ( CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_OFFSET ) ))
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_ADR(_BASE) (( ( _BASE ) + ( CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_OFFSET ) ))
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_ADR(_BASE) (( ( _BASE ) + ( CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_OFFSET ) ))
#define CMNANA_REFCKBUF_MSG_CMNREFCKBUF_SPARE0_ADR(_BASE) (( ( _BASE ) + ( CMNANA_REFCKBUF_MSG_CMNREFCKBUF_SPARE0_OFFSET ) ))

// ******************************************* /Address Space

//************************************************ RegisterStructs


/** @brief CMNANA_REFCKBUF_REGS_MSG_CMNANA_REFCKBUF_REGS_CMNBSCAN_CTRL0 register description at address offset 0x0
  *
  * Register default value:        0x00800080
  * Register full path in IP: CMNANA_REFCKBUF_regs_MSG/CMNANA_REFCKBUF_regs/cmnbscan_ctrl0
  * cmnbscan_ctrl0
  */

typedef union {
  struct {
    uint32_t REFCKTX0_BSCAN_HICM : 1;
    ///< ---
    ///< AccessType="RW" BitOffset="0" ResetValue="0x0"
    uint32_t REFCKTX0_HIHYST : 1;
    ///< ---
    ///< AccessType="RW" BitOffset="1" ResetValue="0x0"
    uint32_t REFCKTX0_SCAN_VREF : 3;
    ///< ---
    ///< AccessType="RW" BitOffset="2" ResetValue="0x0"
    uint32_t REFCKTX0_TERMCAL : 4;
    ///< output resistance cal-code (based on rcomp LUT*)
    ///< AccessType="RW" BitOffset="5" ResetValue="0x4"
    uint32_t  : 7;
    ///< Reserved
    ///< AccessType="RO" BitOffset="9" ResetValue="None"
    uint32_t REFCKTX1_BSCAN_HICM : 1;
    ///< ---
    ///< AccessType="RW" BitOffset="16" ResetValue="0x0"
    uint32_t REFCKTX1_HIHYST : 1;
    ///< ---
    ///< AccessType="RW" BitOffset="17" ResetValue="0x0"
    uint32_t REFCKTX1_SCAN_VREF : 3;
    ///< ---
    ///< AccessType="RW" BitOffset="18" ResetValue="0x0"
    uint32_t REFCKTX1_TERMCAL : 4;
    ///< output resistance cal-code (based on rcomp LUT*)
    ///< AccessType="RW" BitOffset="21" ResetValue="0x4"
    uint32_t  : 7;
    ///< Reserved
    ///< AccessType="RO" BitOffset="25" ResetValue="None"
  } ;
  uint32_t value;
} cmnana_refckbuf_msg_cmnbscan_ctrl0_reg_t;

#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_DEFAULT (0x00800080U)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_RD_MASK (0x01ff01ffU)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_WR_MASK (0x01ff01ffU)


#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX0_BSCAN_HICM_BF_OFF ( 0)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX0_BSCAN_HICM_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX0_BSCAN_HICM_BF_MSK (0x00000001)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX0_BSCAN_HICM_BF_DEF (0x00000000)

#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX0_HIHYST_BF_OFF ( 1)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX0_HIHYST_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX0_HIHYST_BF_MSK (0x00000002)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX0_HIHYST_BF_DEF (0x00000000)

#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX0_SCAN_VREF_BF_OFF ( 2)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX0_SCAN_VREF_BF_WID ( 3)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX0_SCAN_VREF_BF_MSK (0x0000001C)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX0_SCAN_VREF_BF_DEF (0x00000000)

///< output resistance cal-code (based on rcomp LUT*)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX0_TERMCAL_BF_OFF ( 5)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX0_TERMCAL_BF_WID ( 4)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX0_TERMCAL_BF_MSK (0x000001E0)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX0_TERMCAL_BF_DEF (0x00000080)

#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX1_BSCAN_HICM_BF_OFF (16)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX1_BSCAN_HICM_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX1_BSCAN_HICM_BF_MSK (0x00010000)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX1_BSCAN_HICM_BF_DEF (0x00000000)

#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX1_HIHYST_BF_OFF (17)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX1_HIHYST_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX1_HIHYST_BF_MSK (0x00020000)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX1_HIHYST_BF_DEF (0x00000000)

#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX1_SCAN_VREF_BF_OFF (18)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX1_SCAN_VREF_BF_WID ( 3)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX1_SCAN_VREF_BF_MSK (0x001C0000)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX1_SCAN_VREF_BF_DEF (0x00000000)

///< output resistance cal-code (based on rcomp LUT*)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX1_TERMCAL_BF_OFF (21)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX1_TERMCAL_BF_WID ( 4)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX1_TERMCAL_BF_MSK (0x01E00000)
#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REFCKTX1_TERMCAL_BF_DEF (0x00800000)


/** @brief CMNANA_REFCKBUF_REGS_MSG_CMNANA_REFCKBUF_REGS_CMNREFCKPAD0_CTRL0 register description at address offset 0x4
  *
  * Register default value:        0x00000420
  * Register full path in IP: CMNANA_REFCKBUF_regs_MSG/CMNANA_REFCKBUF_regs/cmnrefckpad0_ctrl0
  * cmnrefckpad0_ctrl0
  */

typedef union {
  struct {
    uint32_t REFCKBUF0_TO_SOC_EN : 1;
    ///< 0: disable output clock to dpma1: enable output clock to dpma
    ///< AccessType="RW" BitOffset="0" ResetValue="0x0"
    uint32_t REFCKBUF0_FROM_SOC_EN : 1;
    ///< 0: disable input clock from soc1: enable input clock from soc
    ///< AccessType="RW" BitOffset="1" ResetValue="0x0"
    uint32_t REFCKBUF0_SEL_PATH_EN : 1;
    ///< 0: disable output clock to refck_sel1: enable output clock to refck_sel
    ///< AccessType="RW" BitOffset="2" ResetValue="0x0"
    uint32_t REFCKBUF0_SWFAB_PATH_EN : 1;
    ///< 0: disable output clock to swfabric1: enable output clock to swfabric
    ///< AccessType="RW" BitOffset="3" ResetValue="0x0"
    uint32_t REFCKBUF0_TERM_COARSE : 1;
    ///< ictl_term_coarse=0 --> 85-Ohm modeictl_term_coarse=1 --> 100-Ohm mode
    ///< AccessType="RW" BitOffset="4" ResetValue="0x0"
    uint32_t REFCKBUF0_TERM_MODE : 2;
    ///< sets the termination mode00: termination to ground01: termination
    ///< to  termv  voltage10: floating termiantion11: not used
    ///< AccessType="RW" BitOffset="5" ResetValue="0x1"
    uint32_t REFCKBUF0_TERMCAL_FINE : 4;
    ///< ictl_reftermcal_nt_<3>=TRIMCODE_RX_4
    ///< ictl_reftermcal_nt_<2>=TRIMCODE_RX_3 ictl_reftermcal_nt_<1>=TRIMCODE_RX_2ictl_reftermcal_nt_<0>=
    ///< TRMCODE_RX_1
    ///< AccessType="RW" BitOffset="7" ResetValue="0x8"
    uint32_t REFCKBUF0_DCMON_EN : 1;
    ///< 1: dcmon enabled
    ///< AccessType="RW" BitOffset="11" ResetValue="0x0"
    uint32_t REFCKBUF0_NTL_HIGH_EN : 1;
    ///< 1: xiock_ref_n bump is pulled to pa_vdd1 (in NTL mode)
    ///< AccessType="RW" BitOffset="12" ResetValue="0x0"
    uint32_t REFCKBUF0_NTL_LOW_EN : 1;
    ///< 1: xiock_ref_n bump is pulled to gnd (in NTL mode)
    ///< AccessType="RW" BitOffset="13" ResetValue="0x0"
    uint32_t REFCKBUF0_REF_PD_B : 1;
    ///< 0: Buffer is powered down
    ///< AccessType="RW" BitOffset="14" ResetValue="0x0"
    uint32_t  : 17;
    ///< Reserved
    ///< AccessType="RO" BitOffset="15" ResetValue="None"
  } ;
  uint32_t value;
} cmnana_refckbuf_msg_cmnrefckpad0_ctrl0_reg_t;

#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_DEFAULT (0x00000420U)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_RD_MASK (0x00007fffU)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_WR_MASK (0x00007fffU)


///< 0: disable output clock to dpma1: enable output clock to dpma
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_TO_SOC_EN_BF_OFF ( 0)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_TO_SOC_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_TO_SOC_EN_BF_MSK (0x00000001)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_TO_SOC_EN_BF_DEF (0x00000000)

///< 0: disable input clock from soc1: enable input clock from soc
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_FROM_SOC_EN_BF_OFF ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_FROM_SOC_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_FROM_SOC_EN_BF_MSK (0x00000002)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_FROM_SOC_EN_BF_DEF (0x00000000)

///< 0: disable output clock to refck_sel1: enable output clock to refck_sel
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_SEL_PATH_EN_BF_OFF ( 2)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_SEL_PATH_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_SEL_PATH_EN_BF_MSK (0x00000004)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_SEL_PATH_EN_BF_DEF (0x00000000)

///< 0: disable output clock to swfabric1: enable output clock to swfabric
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_SWFAB_PATH_EN_BF_OFF ( 3)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_SWFAB_PATH_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_SWFAB_PATH_EN_BF_MSK (0x00000008)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_SWFAB_PATH_EN_BF_DEF (0x00000000)

///< ictl_term_coarse=0 --> 85-Ohm modeictl_term_coarse=1 --> 100-Ohm mode
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_TERM_COARSE_BF_OFF ( 4)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_TERM_COARSE_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_TERM_COARSE_BF_MSK (0x00000010)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_TERM_COARSE_BF_DEF (0x00000000)

///< sets the termination mode00: termination to ground01: termination
///< to  termv  voltage10: floating termiantion11: not used
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_TERM_MODE_BF_OFF ( 5)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_TERM_MODE_BF_WID ( 2)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_TERM_MODE_BF_MSK (0x00000060)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_TERM_MODE_BF_DEF (0x00000020)

///< ictl_reftermcal_nt_<3>=TRIMCODE_RX_4
///< ictl_reftermcal_nt_<2>=TRIMCODE_RX_3 ictl_reftermcal_nt_<1>=TRIMCODE_RX_2ictl_reftermcal_nt_<0>=
///< TRMCODE_RX_1
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_TERMCAL_FINE_BF_OFF ( 7)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_TERMCAL_FINE_BF_WID ( 4)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_TERMCAL_FINE_BF_MSK (0x00000780)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_TERMCAL_FINE_BF_DEF (0x00000400)

///< 1: dcmon enabled
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_DCMON_EN_BF_OFF (11)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_DCMON_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_DCMON_EN_BF_MSK (0x00000800)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_DCMON_EN_BF_DEF (0x00000000)

///< 1: xiock_ref_n bump is pulled to pa_vdd1 (in NTL mode)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_NTL_HIGH_EN_BF_OFF (12)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_NTL_HIGH_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_NTL_HIGH_EN_BF_MSK (0x00001000)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_NTL_HIGH_EN_BF_DEF (0x00000000)

///< 1: xiock_ref_n bump is pulled to gnd (in NTL mode)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_NTL_LOW_EN_BF_OFF (13)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_NTL_LOW_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_NTL_LOW_EN_BF_MSK (0x00002000)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_NTL_LOW_EN_BF_DEF (0x00000000)

///< 0: Buffer is powered down
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_REF_PD_B_BF_OFF (14)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_REF_PD_B_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_REF_PD_B_BF_MSK (0x00004000)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REFCKBUF0_REF_PD_B_BF_DEF (0x00000000)


/** @brief CMNANA_REFCKBUF_REGS_MSG_CMNANA_REFCKBUF_REGS_CMNREFCKPAD1_CTRL0 register description at address offset 0x8
  *
  * Register default value:        0x00000020
  * Register full path in IP: CMNANA_REFCKBUF_regs_MSG/CMNANA_REFCKBUF_regs/cmnrefckpad1_ctrl0
  * cmnrefckpad1_ctrl0
  */

typedef union {
  struct {
    uint32_t REFCKBUF1_TO_SOC_EN : 1;
    ///< 0: disable output clock to dpma1: enable output clock to dpma
    ///< AccessType="RW" BitOffset="0" ResetValue="0x0"
    uint32_t REFCKBUF1_FROM_SOC_EN : 1;
    ///< 0: disable input clock from soc1: enable input clock from soc
    ///< AccessType="RW" BitOffset="1" ResetValue="0x0"
    uint32_t REFCKBUF1_SEL_PATH_EN : 1;
    ///< 0: disable output clock to refck_sel1: enable output clock to refck_sel
    ///< AccessType="RW" BitOffset="2" ResetValue="0x0"
    uint32_t REFCKBUF1_SWFAB_PATH_EN : 1;
    ///< 0: disable output clock to swfabric1: enable output clock to swfabric
    ///< AccessType="RW" BitOffset="3" ResetValue="0x0"
    uint32_t REFCKBUF1_TERM_COARSE : 1;
    ///< ictl_term_coarse=0 --> 85-Ohm modeictl_term_coarse=1 --> 100-Ohm mode
    ///< AccessType="RW" BitOffset="4" ResetValue="0x0"
    uint32_t REFCKBUF1_TERM_MODE : 2;
    ///< sets the termination mode00: termination to ground01: termination
    ///< to  termv  voltage10: floating termiantion11: not used
    ///< AccessType="RW" BitOffset="5" ResetValue="0x1"
    uint32_t REFCKBUF1_TERMCAL_FINE : 4;
    ///< ictl_reftermcal_nt_<3>=TRIMCODE_RX_4
    ///< ictl_reftermcal_nt_<2>=TRIMCODE_RX_3 ictl_reftermcal_nt_<1>=TRIMCODE_RX_2ictl_reftermcal_nt_<0>=
    ///< TRMCODE_RX_1
    ///< AccessType="RW" BitOffset="7" ResetValue="0x0"
    uint32_t REFCKBUF1_DCMON_EN : 1;
    ///< 1: dcmon enabled
    ///< AccessType="RW" BitOffset="11" ResetValue="0x0"
    uint32_t REFCKBUF1_NTL_HIGH_EN : 1;
    ///< 1: xiock_ref_n bump is pulled to pa_vdd1 (in NTL mode)
    ///< AccessType="RW" BitOffset="12" ResetValue="0x0"
    uint32_t REFCKBUF1_NTL_LOW_EN : 1;
    ///< 1: xiock_ref_n bump is pulled to gnd (in NTL mode)
    ///< AccessType="RW" BitOffset="13" ResetValue="0x0"
    uint32_t REFCKBUF1_REF_PD_B : 1;
    ///< 0: Buffer is powered down
    ///< AccessType="RW" BitOffset="14" ResetValue="0x0"
    uint32_t  : 17;
    ///< Reserved
    ///< AccessType="RO" BitOffset="15" ResetValue="None"
  } ;
  uint32_t value;
} cmnana_refckbuf_msg_cmnrefckpad1_ctrl0_reg_t;

#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_DEFAULT (0x00000020U)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_RD_MASK (0x00007fffU)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_WR_MASK (0x00007fffU)


///< 0: disable output clock to dpma1: enable output clock to dpma
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_TO_SOC_EN_BF_OFF ( 0)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_TO_SOC_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_TO_SOC_EN_BF_MSK (0x00000001)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_TO_SOC_EN_BF_DEF (0x00000000)

///< 0: disable input clock from soc1: enable input clock from soc
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_FROM_SOC_EN_BF_OFF ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_FROM_SOC_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_FROM_SOC_EN_BF_MSK (0x00000002)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_FROM_SOC_EN_BF_DEF (0x00000000)

///< 0: disable output clock to refck_sel1: enable output clock to refck_sel
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_SEL_PATH_EN_BF_OFF ( 2)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_SEL_PATH_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_SEL_PATH_EN_BF_MSK (0x00000004)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_SEL_PATH_EN_BF_DEF (0x00000000)

///< 0: disable output clock to swfabric1: enable output clock to swfabric
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_SWFAB_PATH_EN_BF_OFF ( 3)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_SWFAB_PATH_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_SWFAB_PATH_EN_BF_MSK (0x00000008)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_SWFAB_PATH_EN_BF_DEF (0x00000000)

///< ictl_term_coarse=0 --> 85-Ohm modeictl_term_coarse=1 --> 100-Ohm mode
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_TERM_COARSE_BF_OFF ( 4)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_TERM_COARSE_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_TERM_COARSE_BF_MSK (0x00000010)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_TERM_COARSE_BF_DEF (0x00000000)

///< sets the termination mode00: termination to ground01: termination
///< to  termv  voltage10: floating termiantion11: not used
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_TERM_MODE_BF_OFF ( 5)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_TERM_MODE_BF_WID ( 2)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_TERM_MODE_BF_MSK (0x00000060)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_TERM_MODE_BF_DEF (0x00000020)

///< ictl_reftermcal_nt_<3>=TRIMCODE_RX_4
///< ictl_reftermcal_nt_<2>=TRIMCODE_RX_3 ictl_reftermcal_nt_<1>=TRIMCODE_RX_2ictl_reftermcal_nt_<0>=
///< TRMCODE_RX_1
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_TERMCAL_FINE_BF_OFF ( 7)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_TERMCAL_FINE_BF_WID ( 4)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_TERMCAL_FINE_BF_MSK (0x00000780)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_TERMCAL_FINE_BF_DEF (0x00000000)

///< 1: dcmon enabled
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_DCMON_EN_BF_OFF (11)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_DCMON_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_DCMON_EN_BF_MSK (0x00000800)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_DCMON_EN_BF_DEF (0x00000000)

///< 1: xiock_ref_n bump is pulled to pa_vdd1 (in NTL mode)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_NTL_HIGH_EN_BF_OFF (12)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_NTL_HIGH_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_NTL_HIGH_EN_BF_MSK (0x00001000)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_NTL_HIGH_EN_BF_DEF (0x00000000)

///< 1: xiock_ref_n bump is pulled to gnd (in NTL mode)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_NTL_LOW_EN_BF_OFF (13)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_NTL_LOW_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_NTL_LOW_EN_BF_MSK (0x00002000)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_NTL_LOW_EN_BF_DEF (0x00000000)

///< 0: Buffer is powered down
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_REF_PD_B_BF_OFF (14)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_REF_PD_B_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_REF_PD_B_BF_MSK (0x00004000)
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REFCKBUF1_REF_PD_B_BF_DEF (0x00000000)


/** @brief CMNANA_REFCKBUF_REGS_MSG_CMNANA_REFCKBUF_REGS_CMNREFCK_MISC0 register description at address offset 0xc
  *
  * Register default value:        0x00000002
  * Register full path in IP: CMNANA_REFCKBUF_regs_MSG/CMNANA_REFCKBUF_regs/cmnrefck_misc0
  * cmnrefck_misc0
  */

typedef union {
  struct {
    uint32_t REG_REFCKBUF0_BLEED_TUNE : 3;
    ///< control for a bleeding current value<2:0> = 111: highest bleed current<2:0>
    ///< = 000: lowest bleed current
    ///< AccessType="RW" BitOffset="0" ResetValue="0x2"
    uint32_t REG_REFCKBUF0_PD_B : 1;
    ///< power down for regulator
    ///< AccessType="RW" BitOffset="3" ResetValue="0x0"
    uint32_t REFCKBUF0_HICM : 1;
    ///< for refck buffer, both 0 and 1 are the same
    ///< AccessType="RW" BitOffset="4" ResetValue="0x0"
    uint32_t REG_REFCKBUF0_DCMON_SEL : 3;
    ///< ---
    ///< AccessType="RW" BitOffset="5" ResetValue="0x0"
    uint32_t REFCKBUF0_HSMON_EN : 1;
    ///< 1: hsmon enabled
    ///< AccessType="RW" BitOffset="8" ResetValue="0x0"
    uint32_t  : 23;
    ///< Reserved
    ///< AccessType="RO" BitOffset="9" ResetValue="None"
  } ;
  uint32_t value;
} cmnana_refckbuf_msg_cmnrefck_misc0_reg_t;

#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_DEFAULT (0x00000002U)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_RD_MASK (0x000001ffU)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_WR_MASK (0x000001ffU)


///< control for a bleeding current value<2:0> = 111: highest bleed current<2:0>
///< = 000: lowest bleed current
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_BLEED_TUNE_BF_OFF ( 0)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_BLEED_TUNE_BF_WID ( 3)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_BLEED_TUNE_BF_MSK (0x00000007)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_BLEED_TUNE_BF_DEF (0x00000002)

///< power down for regulator
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_PD_B_BF_OFF ( 3)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_PD_B_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_PD_B_BF_MSK (0x00000008)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_PD_B_BF_DEF (0x00000000)

///< for refck buffer, both 0 and 1 are the same
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_HICM_BF_OFF ( 4)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_HICM_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_HICM_BF_MSK (0x00000010)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_HICM_BF_DEF (0x00000000)

#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_DCMON_SEL_BF_OFF ( 5)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_DCMON_SEL_BF_WID ( 3)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_DCMON_SEL_BF_MSK (0x000000E0)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_DCMON_SEL_BF_DEF (0x00000000)

///< 1: hsmon enabled
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_HSMON_EN_BF_OFF ( 8)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_HSMON_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_HSMON_EN_BF_MSK (0x00000100)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REFCKBUF0_HSMON_EN_BF_DEF (0x00000000)


/** @brief CMNANA_REFCKBUF_REGS_MSG_CMNANA_REFCKBUF_REGS_CMNREFCK_MISC1 register description at address offset 0x10
  *
  * Register default value:        0x00000002
  * Register full path in IP: CMNANA_REFCKBUF_regs_MSG/CMNANA_REFCKBUF_regs/cmnrefck_misc1
  * cmnrefck_misc1
  */

typedef union {
  struct {
    uint32_t REG_REFCKBUF1_BLEED_TUNE : 3;
    ///< control for a bleeding current value<2:0> = 111: highest bleed current<2:0>
    ///< = 000: lowest bleed current
    ///< AccessType="RW" BitOffset="0" ResetValue="0x2"
    uint32_t REG_REFCKBUF1_PD_B : 1;
    ///< power down for regulator
    ///< AccessType="RW" BitOffset="3" ResetValue="0x0"
    uint32_t REFCKBUF1_HICM : 1;
    ///< for refck buffer, both 0 and 1 are the same
    ///< AccessType="RW" BitOffset="4" ResetValue="0x0"
    uint32_t REG_REFCKBUF1_DCMON_SEL : 3;
    ///< ---
    ///< AccessType="RW" BitOffset="5" ResetValue="0x0"
    uint32_t REFCKBUF1_HSMON_EN : 1;
    ///< 1: hsmon enabled
    ///< AccessType="RW" BitOffset="8" ResetValue="0x0"
    uint32_t  : 23;
    ///< Reserved
    ///< AccessType="RO" BitOffset="9" ResetValue="None"
  } ;
  uint32_t value;
} cmnana_refckbuf_msg_cmnrefck_misc1_reg_t;

#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_DEFAULT (0x00000002U)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_RD_MASK (0x000001ffU)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_WR_MASK (0x000001ffU)


///< control for a bleeding current value<2:0> = 111: highest bleed current<2:0>
///< = 000: lowest bleed current
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_BLEED_TUNE_BF_OFF ( 0)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_BLEED_TUNE_BF_WID ( 3)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_BLEED_TUNE_BF_MSK (0x00000007)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_BLEED_TUNE_BF_DEF (0x00000002)

///< power down for regulator
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_PD_B_BF_OFF ( 3)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_PD_B_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_PD_B_BF_MSK (0x00000008)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_PD_B_BF_DEF (0x00000000)

///< for refck buffer, both 0 and 1 are the same
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_HICM_BF_OFF ( 4)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_HICM_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_HICM_BF_MSK (0x00000010)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_HICM_BF_DEF (0x00000000)

#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_DCMON_SEL_BF_OFF ( 5)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_DCMON_SEL_BF_WID ( 3)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_DCMON_SEL_BF_MSK (0x000000E0)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_DCMON_SEL_BF_DEF (0x00000000)

///< 1: hsmon enabled
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_HSMON_EN_BF_OFF ( 8)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_HSMON_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_HSMON_EN_BF_MSK (0x00000100)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REFCKBUF1_HSMON_EN_BF_DEF (0x00000000)


/** @brief CMNANA_REFCKBUF_REGS_MSG_CMNANA_REFCKBUF_REGS_CMNREFCK_MISC2 register description at address offset 0x14
  *
  * Register default value:        0x00000620
  * Register full path in IP: CMNANA_REFCKBUF_regs_MSG/CMNANA_REFCKBUF_regs/cmnrefck_misc2
  * cmnrefck_misc2
  */

typedef union {
  struct {
    uint32_t REG_REFCKBUF0_STG1_BYP_EN : 1;
    ///< ---
    ///< AccessType="RW" BitOffset="0" ResetValue="0x0"
    uint32_t REG_REFCKBUF0_STG2_BYP_EN : 1;
    ///< ---
    ///< AccessType="RW" BitOffset="1" ResetValue="0x0"
    uint32_t REG_REFCKBUF1_STG1_BYP_EN : 1;
    ///< ---
    ///< AccessType="RW" BitOffset="2" ResetValue="0x0"
    uint32_t REG_REFCKBUF1_STG2_BYP_EN : 1;
    ///< ---
    ///< AccessType="RW" BitOffset="3" ResetValue="0x0"
    uint32_t REFGEN_BLEED_TUNE : 3;
    ///< bleeder current for stabiity control
    ///< AccessType="RW" BitOffset="4" ResetValue="0x2"
    uint32_t REFCKBUF0_NTL_OUT_SEL : 1;
    ///< ---
    ///< AccessType="RW" BitOffset="7" ResetValue="0x0"
    uint32_t REFCKBUF1_NTL_OUT_SEL : 1;
    ///< ---
    ///< AccessType="RW" BitOffset="8" ResetValue="0x0"
    uint32_t REFCKBUF0_TO_DPMA_EN : 1;
    ///< ---
    ///< AccessType="RW" BitOffset="9" ResetValue="0x1"
    uint32_t REFCKBUF1_TO_DPMA_EN : 1;
    ///< ---
    ///< AccessType="RW" BitOffset="10" ResetValue="0x1"
    uint32_t  : 21;
    ///< Reserved
    ///< AccessType="RO" BitOffset="11" ResetValue="None"
  } ;
  uint32_t value;
} cmnana_refckbuf_msg_cmnrefck_misc2_reg_t;

#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_DEFAULT (0x00000620U)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_RD_MASK (0x000007ffU)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_WR_MASK (0x000007ffU)


#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF0_STG1_BYP_EN_BF_OFF ( 0)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF0_STG1_BYP_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF0_STG1_BYP_EN_BF_MSK (0x00000001)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF0_STG1_BYP_EN_BF_DEF (0x00000000)

#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF0_STG2_BYP_EN_BF_OFF ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF0_STG2_BYP_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF0_STG2_BYP_EN_BF_MSK (0x00000002)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF0_STG2_BYP_EN_BF_DEF (0x00000000)

#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF1_STG1_BYP_EN_BF_OFF ( 2)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF1_STG1_BYP_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF1_STG1_BYP_EN_BF_MSK (0x00000004)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF1_STG1_BYP_EN_BF_DEF (0x00000000)

#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF1_STG2_BYP_EN_BF_OFF ( 3)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF1_STG2_BYP_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF1_STG2_BYP_EN_BF_MSK (0x00000008)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF1_STG2_BYP_EN_BF_DEF (0x00000000)

///< bleeder current for stabiity control
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFGEN_BLEED_TUNE_BF_OFF ( 4)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFGEN_BLEED_TUNE_BF_WID ( 3)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFGEN_BLEED_TUNE_BF_MSK (0x00000070)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFGEN_BLEED_TUNE_BF_DEF (0x00000020)

#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF0_NTL_OUT_SEL_BF_OFF ( 7)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF0_NTL_OUT_SEL_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF0_NTL_OUT_SEL_BF_MSK (0x00000080)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF0_NTL_OUT_SEL_BF_DEF (0x00000000)

#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF1_NTL_OUT_SEL_BF_OFF ( 8)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF1_NTL_OUT_SEL_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF1_NTL_OUT_SEL_BF_MSK (0x00000100)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF1_NTL_OUT_SEL_BF_DEF (0x00000000)

#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF0_TO_DPMA_EN_BF_OFF ( 9)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF0_TO_DPMA_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF0_TO_DPMA_EN_BF_MSK (0x00000200)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF0_TO_DPMA_EN_BF_DEF (0x00000200)

#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF1_TO_DPMA_EN_BF_OFF (10)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF1_TO_DPMA_EN_BF_WID ( 1)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF1_TO_DPMA_EN_BF_MSK (0x00000400)
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REFCKBUF1_TO_DPMA_EN_BF_DEF (0x00000400)


/** @brief CMNANA_REFCKBUF_REGS_MSG_CMNANA_REFCKBUF_REGS_CMNREFCKBUF_SPARE0 register description at address offset 0x18
  *
  * Register default value:        0x00000080
  * Register full path in IP: CMNANA_REFCKBUF_regs_MSG/CMNANA_REFCKBUF_regs/cmnrefckbuf_spare0
  * cmnrefckbuf_spare0
  */

typedef union {
  struct {
    uint32_t CMN_REFCKBUF_SPARE : 8;
    ///< ---
    ///< AccessType="RW" BitOffset="0" ResetValue="0x80"
    uint32_t  : 24;
    ///< Reserved
    ///< AccessType="RO" BitOffset="8" ResetValue="None"
  } ;
  uint32_t value;
} cmnana_refckbuf_msg_cmnrefckbuf_spare0_reg_t;

#define CMNANA_REFCKBUF_MSG_CMNREFCKBUF_SPARE0_DEFAULT (0x00000080U)
#define CMNANA_REFCKBUF_MSG_CMNREFCKBUF_SPARE0_RD_MASK (0x000000ffU)
#define CMNANA_REFCKBUF_MSG_CMNREFCKBUF_SPARE0_WR_MASK (0x000000ffU)


#define CMNANA_REFCKBUF_MSG_CMNREFCKBUF_SPARE0_CMN_REFCKBUF_SPARE_BF_OFF ( 0)
#define CMNANA_REFCKBUF_MSG_CMNREFCKBUF_SPARE0_CMN_REFCKBUF_SPARE_BF_WID ( 8)
#define CMNANA_REFCKBUF_MSG_CMNREFCKBUF_SPARE0_CMN_REFCKBUF_SPARE_BF_MSK (0x000000FF)
#define CMNANA_REFCKBUF_MSG_CMNREFCKBUF_SPARE0_CMN_REFCKBUF_SPARE_BF_DEF (0x00000080)

//************************************************ /RegisterStructs


// ******************************************* Register pointer macros

#define CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_REG(_BASE) ((cmnana_refckbuf_msg_cmnbscan_ctrl0_reg_t*) CMNANA_REFCKBUF_MSG_CMNBSCAN_CTRL0_ADR(_BASE))
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_REG(_BASE) ((cmnana_refckbuf_msg_cmnrefckpad0_ctrl0_reg_t*) CMNANA_REFCKBUF_MSG_CMNREFCKPAD0_CTRL0_ADR(_BASE))
#define CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_REG(_BASE) ((cmnana_refckbuf_msg_cmnrefckpad1_ctrl0_reg_t*) CMNANA_REFCKBUF_MSG_CMNREFCKPAD1_CTRL0_ADR(_BASE))
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_REG(_BASE) ((cmnana_refckbuf_msg_cmnrefck_misc0_reg_t*) CMNANA_REFCKBUF_MSG_CMNREFCK_MISC0_ADR(_BASE))
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_REG(_BASE) ((cmnana_refckbuf_msg_cmnrefck_misc1_reg_t*) CMNANA_REFCKBUF_MSG_CMNREFCK_MISC1_ADR(_BASE))
#define CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_REG(_BASE) ((cmnana_refckbuf_msg_cmnrefck_misc2_reg_t*) CMNANA_REFCKBUF_MSG_CMNREFCK_MISC2_ADR(_BASE))
#define CMNANA_REFCKBUF_MSG_CMNREFCKBUF_SPARE0_REG(_BASE) ((cmnana_refckbuf_msg_cmnrefckbuf_spare0_reg_t*) CMNANA_REFCKBUF_MSG_CMNREFCKBUF_SPARE0_ADR(_BASE))

// ******************************************* /Register pointer macros


// ******************************************* AddressSpace struct
typedef struct
{
    cmnana_refckbuf_msg_cmnbscan_ctrl0_reg_t CMNBSCAN_CTRL0; /*< Address offset = 0x0 */
    cmnana_refckbuf_msg_cmnrefckpad0_ctrl0_reg_t CMNREFCKPAD0_CTRL0; /*< Address offset = 0x4 */
    cmnana_refckbuf_msg_cmnrefckpad1_ctrl0_reg_t CMNREFCKPAD1_CTRL0; /*< Address offset = 0x8 */
    cmnana_refckbuf_msg_cmnrefck_misc0_reg_t CMNREFCK_MISC0; /*< Address offset = 0xc */
    cmnana_refckbuf_msg_cmnrefck_misc1_reg_t CMNREFCK_MISC1; /*< Address offset = 0x10 */
    cmnana_refckbuf_msg_cmnrefck_misc2_reg_t CMNREFCK_MISC2; /*< Address offset = 0x14 */
    cmnana_refckbuf_msg_cmnrefckbuf_spare0_reg_t CMNREFCKBUF_SPARE0; /*< Address offset = 0x18 */
} cmnana_refckbuf_msg_t;     // size: 0x001c

// AddressSpace struct pointer
//
#define DLNK_JESD0_PHY_PMA0_CMNANA_REFCKBUF  ((cmnana_refckbuf_msg_t*) DLNK_JESD0_PHY_PMA0_CMNANA_REFCKBUF_BASE)
#define DLNK_JESD1_PHY_PMA0_CMNANA_REFCKBUF  ((cmnana_refckbuf_msg_t*) DLNK_JESD1_PHY_PMA0_CMNANA_REFCKBUF_BASE)
#define DLNK_JESD2_PHY_PMA0_CMNANA_REFCKBUF  ((cmnana_refckbuf_msg_t*) DLNK_JESD2_PHY_PMA0_CMNANA_REFCKBUF_BASE)
#define DLNK_JESD3_PHY_PMA0_CMNANA_REFCKBUF  ((cmnana_refckbuf_msg_t*) DLNK_JESD3_PHY_PMA0_CMNANA_REFCKBUF_BASE)

// ******************************************* /Address Space

#endif      // _CMNANA_REFCKBUF_MSG_H_

