#ifndef _DRAM_BRKXMP_H_
#define _DRAM_BRKXMP_H_

// ******************************************************************************
// ------------------------------------------------------------------------------
//                               INTEL CONFIDENTIAL
// ------------------------------------------------------------------------------
//    Copyright (c) 2018 - 2024 Intel Corporation
//
//    This software and the related documents are Intel copyrighted materials,
//    and your use of them is governed by the express license under which they
//    were provided to you ("License").
//    Unless the License provides otherwise, you may not use, modify, copy, publish,
//    distribute, disclose or transmit this software or the related documents
//    without Intel's prior written permission.
//
//    This software and the related documents are provided as is, with no express or
//    implied warranties, other than those that are expressly stated in the License.
// ------------------------------------------------------------------------------
//
//    DO NOT EDIT THIS FILE !!!
//
//    This file has been automatically generated by OneSource
//
// ******************************************************************************

#ifndef __KERNEL__
#include <stdint.h>
#endif // __KERNEL__
// ******************************************* Base address macros

#define DLNK_JESD0_PHY_DRAM_BRKXMP_INST_BASE  ( 0x06300000 )
#define DLNK_JESD1_PHY_DRAM_BRKXMP_INST_BASE  ( 0x06b00000 )
#define DLNK_JESD2_PHY_DRAM_BRKXMP_INST_BASE  ( 0x07300000 )
#define DLNK_JESD3_PHY_DRAM_BRKXMP_INST_BASE  ( 0x07b00000 )

// ******************************************* /Base address macros


// ******************************************* Register offset macros


// ******************************************* /Register offset macros


// ******************************************* AddressSpace macros

// ******************************************* /Address Space

//************************************************ RegisterStructs

//************************************************ /RegisterStructs


// ******************************************* Register pointer macros


// ******************************************* /Register pointer macros


// ******************************************* AddressSpace struct
typedef struct
{
    uint32_t             DRAM_BRKXMP_INST_DRAM_BRKXMP [16384]; /*< Memory at address offset = 0x0 */
} dram_brkxmp_t;     // size: 0x0000

// AddressSpace struct pointer
//
#define DLNK_JESD0_PHY_DRAM_BRKXMP_INST  ((dram_brkxmp_t*) DLNK_JESD0_PHY_DRAM_BRKXMP_INST_BASE)
#define DLNK_JESD1_PHY_DRAM_BRKXMP_INST  ((dram_brkxmp_t*) DLNK_JESD1_PHY_DRAM_BRKXMP_INST_BASE)
#define DLNK_JESD2_PHY_DRAM_BRKXMP_INST  ((dram_brkxmp_t*) DLNK_JESD2_PHY_DRAM_BRKXMP_INST_BASE)
#define DLNK_JESD3_PHY_DRAM_BRKXMP_INST  ((dram_brkxmp_t*) DLNK_JESD3_PHY_DRAM_BRKXMP_INST_BASE)

// ******************************************* /Address Space

#endif      // _DRAM_BRKXMP_H_

