# --------------------------------------------------------------------------------
# -- REQUIRED:  DO NOT REMOVE THESE STATEMENTS; DO NOT ALTER STATEMENT ORDER
# --------------------------------------------------------------------------------


#-- HWC Project Level Makefile for VCS
include ${WORKAREA}/project_tools/verif/vcs/Makefile


# -----------------------------------------------------------------------------------
# -- Locally Defined Makefile Targets 
# -----------------------------------------------------------------------------------