#ifndef _SRAM_CAP_H_

// ******************************************************************************
// ------------------------------------------------------------------------------
//                               INTEL CONFIDENTIAL
// ------------------------------------------------------------------------------
//    Copyright (c) 2018 - 2024 Intel Corporation
//
//    This software and the related documents are Intel copyrighted materials,
//    and your use of them is governed by the express license under which they
//    were provided to you ("License").
//    Unless the License provides otherwise, you may not use, modify, copy, publish,
//    distribute, disclose or transmit this software or the related documents
//    without Intel's prior written permission.
//
//    This software and the related documents are provided as is, with no express or
//    implied warranties, other than those that are expressly stated in the License.
// ------------------------------------------------------------------------------
//
//    DO NOT EDIT THIS FILE !!!
//
//    This file has been automatically generated by OneSource
//
// ******************************************************************************

#ifndef __KERNEL__
#include <stdint.h>
#endif // __KERNEL__
// ******************************************* Base address macros

#define MEM_CAP0_SRAM_BASE    ( 0x04000000 )
#define MEM_CAP1_SRAM_BASE    ( 0x04200000 )

// ******************************************* /Base address macros

#define SRAM_CAP_MEM_CELL_CAP_ARR_SZ0 (114688)
// ******************************************* AddressSpace struct
typedef struct
{
    uint128_t MEM_CELL_CAP[114688]; /*< Address offset = 0x0 (128 bit) */
} sram_cap_t;     // size: 0x0010

// AddressSpace struct pointer
//
#define MEM_CAP0_SRAM    ((sram_cap_t*) MEM_CAP0_SRAM_BASE)
#define MEM_CAP1_SRAM    ((sram_cap_t*) MEM_CAP1_SRAM_BASE)

// ******************************************* /Address Space

#endif      // _SRAM_CAP_H_

