# --------------------------------------------------------------------------------
# -- REQUIRED:  DO NOT REMOVE THESE STATEMENTS; DO NOT ALTER STATEMENT ORDER
# --------------------------------------------------------------------------------


#-- HWC Project Level Makefile for iFLOW
include ${WORKAREA}/project_tools/iflow/Makefile


# -----------------------------------------------------------------------------------
# -- Locally Defined Makefile Targets 
# -----------------------------------------------------------------------------------