/* INTEL CONFIDENTIAL
 *
 * Copyright 2024 Intel Corporation All Rights Reserved.
 *
 * The source code contained or described herein and all documents related
 * to the source code ("Material") are owned by Intel Corporation or its
 * suppliers or licensors. Title to the Material remains with Intel
 * Corporation or its suppliers and licensors. The Material contains trade
 * secrets and proprietary and confidential information of Intel or its
 * suppliers and licensors. The Material is protected by worldwide copyright
 * and trade secret laws and treaty provisions. No part of the Material
 * may be used, copied, reproduced, modified, published, uploaded, posted,
 * transmitted, distributed, or disclosed in any way without Intel's prior
 * express written permission.
 *
 * No license under any patent, copyright, trade secret or other
 * intellectual property right is granted to or conferred upon you by
 * disclosure or delivery of the Materials, either expressly, by
 * implication, inducement, estoppel or otherwise. Any license under such
 * intellectual property rights must be express and approved by Intel in
 * writing.
 *
 *****************************************************************************/

/**
 * this header file is generated by tool, any direct modification without going
 * through the table generation process will get lost
 */

#ifndef __SET_TIME_REF_MSG__
#define __SET_TIME_REF_MSG__

#include <stdint.h>
#include "com_msgs_enum.h"

/*
 * Set the specified time reference index to the BFN time at message reception. The index can be used for subsequent
 * relative messaging.
 */
typedef union {
    struct
    {
        e_opcode_type_t opcode : 16; // opcode
        e_timing_type_t timing : 2;  // unused
        uint32_t ref_index : 4;      // This reference index is updated to refer to the current BFN time. The timing
                                     // information corresponding to this index will be used to calculate the relative offset
                                     // in messages using relative timing mode. The Timestamp specified in this message is
                                     // ignored.
        uint32_t res0 : 10;          // reserved
        uint32_t timestamp;          // unused
    };
    uint32_t value[2];
} set_time_ref_bf_t;

#endif // __SET_TIME_REF_MSG__
