/* INTEL CONFIDENTIAL
 *
 * Copyright 2024 Intel Corporation All Rights Reserved.
 *
 * The source code contained or described herein and all documents related
 * to the source code ("Material") are owned by Intel Corporation or its
 * suppliers or licensors. Title to the Material remains with Intel
 * Corporation or its suppliers and licensors. The Material contains trade
 * secrets and proprietary and confidential information of Intel or its
 * suppliers and licensors. The Material is protected by worldwide copyright
 * and trade secret laws and treaty provisions. No part of the Material
 * may be used, copied, reproduced, modified, published, uploaded, posted,
 * transmitted, distributed, or disclosed in any way without Intel's prior
 * express written permission.
 *
 * No license under any patent, copyright, trade secret or other
 * intellectual property right is granted to or conferred upon you by
 * disclosure or delivery of the Materials, either expressly, by
 * implication, inducement, estoppel or otherwise. Any license under such
 * intellectual property rights must be express and approved by Intel in
 * writing.
 *
 *****************************************************************************/

/**
 * this header file is generated by tool, any direct modification without going
 * through the table generation process will get lost
 */

#ifndef __COM_RM_MSG__
#define __COM_RM_MSG__

#include <stdint.h>

/*
 * radio message for fbr config from TX to RX
 */
typedef union {
    struct
    {
        uint32_t opcode : 16;           // opcode
        uint32_t timing : 2;            // Unused
        uint32_t ref_index : 4;         // Unused
        uint32_t res0 : 10;             // reserved
        uint32_t timestamp;             // Unused
        uint32_t fbr_idx : 8;           // Index into the FBR configuration table
        uint32_t digrf_mixer_freq : 24; // DRF mixing frequency
        uint32_t fbr_mask : 4;          // FBRs used for the band config
        uint32_t resv1 : 28;            // Reserved
    };
    uint32_t value[4];
} rm_fbr_config_bf_t;

#endif // __COM_RM_MSG__
