/*********************************************************************************************
*
* INTEL CONFIDENTIAL
*
* Copyright (C) 2022 Intel Corporation
*
* This software and the related documents ("Material") are Intel copyrighted materials,
* and your use of them is governed by the express license under which they were provided
* to you ("License"). Unless the License provides otherwise, you may not use, modify,
* copy, publish, distribute, disclose or transmit this software or the related documents
* without Intel's prior written permission.
* This software and the related documents are provided as is, with no express or implied
* warranties, other than those that are expressly stated in the License.
* No license under any patent, copyright, trade secret or other intellectual property
* right is granted to or conferred upon you by disclosure or delivery of the Materials,
* either expressly, by implication, inducement, estoppel or otherwise. Any license under
* such intellectual property rights must be expressed and approved by Intel in writing.
*
*********************************************************************************************/
/**
* @file    glue_level_lpbk_32g_5e_24_01_24
* @brief   Code for Glue level external loopback 32g UC 5E- JESD RX glue to JESD TX glue
* @details 1. Configuration of JESD TX IP, JESD TX glue logic, JESD RX IP,JESD RX glue registers
2.Configure loopback register 
* @TC Description:
1. Data is sent from DNRT Tx to JESD RX IP and received at JESD Rx glue
2. Data is looped back from JESD Rx glue to JESD Tx glue
3. From JESD TX IP the data is streamed and captured instantaneously at DNRT RX.
*/
/*********************************************************************************************
* LOCAL INCLUDE STATEMENTS                    *
*********************************************************************************************/
#include "srp.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "com_definitions.h"
#include <stdbool.h>
#include "logger.h"
#include "srp_block_ids.h"
#include "cli.h"
#include "init.h"
#include "all_comps.h"
#include<time.h> 
#include "srpCliCommon.h"
#include "common_macro.h"
#include<time.h> 
//#include "jesd.h"
// later need to port the function declaration to jesd.h
// return value void/int  - paramaterization to be explored

int program_tx_ip_registers();
int program_tx_glue_registers();
int program_rx_ip_registers();
int program_rx_glue_registers();
int program_cmn_csr_registers();
int program_enable_registers();
//int program_bfn_registers();

void delay(unsigned int mseconds);


int main(int argc, char **argv)
{
	printf("Hello from Main\n");
	uint32_t read_value;
	extern void * srp;
	uint32_t error = 0;
	uint32_t write_status = 0;
	uint32_t dev_id =0;
    uint32_t dev_flags = 0;

	uint32_t tx_gb_empty_st = 0;
	uint32_t tx_gb_full_st = 0;
	
	uint32_t curr_tx_gb_empty_st = 0;
	uint32_t curr_tx_gb_full_st = 0;
	
	uint32_t prev_tx_gb_empty_st = 0;
	uint32_t prev_tx_gb_full_st = 0;

	uint32_t flag_tx_gb_empty_st   = 0;
	uint32_t flag_tx_gb_full_st  = 0;
	
	uint32_t count = 0;
	
	uint32_t value   = 0;
	uint32_t value1   = 0;
	uint32_t value2  = 0;
	uint32_t value3  = 0;
	uint32_t value4  = 0;
	uint32_t value5  = 0;
	uint32_t value6  = 0;
	uint32_t value7  = 0;
	uint32_t value8  = 0;
	uint32_t value9  = 0;
	uint32_t value10 = 0;
	uint32_t value11 = 0;
	uint32_t value12 = 0;
	uint32_t value13 = 0;
	uint32_t value14 = 0;
	uint32_t value15 = 0;
	uint32_t value16 = 0;
	uint32_t value17 = 0;
	uint32_t value18 = 0;
	uint32_t value19 = 0;
	uint32_t value20 = 0;
	uint32_t value21 = 0;
	uint32_t value22 = 0;
	uint32_t value23 = 0;
    /* uint32_t value28 = 0;
	uint32_t value32 = 0;
    uint32_t value36 = 0;
    uint32_t value37 = 0; */


	
	// initialize DUT
	init();
	sleep(2);

	LOG_PRINT("INFO: logger beginning\n");
	delay(500);
	printf("Before JESD_EN : Enable clock \n");
	system("frioPciWrite -F s5a1 -P 0x20000 0x14"); //IP
	system("frioPciWrite -F s5b1 -P 0x20000 0x14"); //IP
	delay(500);
	printf("CLOCK Enabled before starting DUT \n");


	//function calls - glue level lpbk - config Tx IP,Rx ip,Rx glue,Tx Glue,cmn csr registers
	program_tx_ip_registers();
	program_rx_ip_registers();
	program_rx_glue_registers();
	program_cmn_csr_registers();
	program_tx_glue_registers();
	//program_bfn_registers();
	
	printf("Giving delay of 10 milli seconds \n");
	delay(10);
	
	//enable loopback - glue level - jesd rx glue to jesd tx glue - lpbk ctl - 0x2
	int i=0;
	uint32_t base_address_cmn[] = {JESDABC_M0_CMN_CSR_BASE,  JESDABC_M1_CMN_CSR_BASE,  JESDABC_M2_CMN_CSR_BASE,  JESDABC_M3_CMN_CSR_BASE};
	printf("JESD CMN CSR CONFIG : program_cmn_csr_registers \n");
	//for(i=0; i<sizeof(base_address_cmn) / sizeof(base_address_cmn[0]); i++)
	for(i=0; i<1; i++)
	{ 		
		write_read_expect_18a(base_address_cmn[i]+JESDABC_CMN_CSR_MEM_LPBK_CTL_OFFSET, JESDABC_CMN_CSR_MEM_LPBK_CTL_DEFAULT, 0x2, 0x2, JESDABC_CMN_CSR_MEM_LPBK_CTL_RD_MASK, JESDABC_CMN_CSR_MEM_LPBK_CTL_WR_MASK, "JESDABC_CMN_CSR_MEM_LPBK_CTL_OFFSET");
	}
	delay(10);
	
	/* open the core, first function to call before initiating any read/write */
    srp_dev_open(dev_id, dev_flags, &srp);
	
	int j=0;	

	uint32_t base_address_tx[] = {JESDABC_M0_XIP_204C_TX_BASE,  JESDABC_M1_XIP_204C_TX_BASE,  JESDABC_M2_XIP_204C_TX_BASE,  JESDABC_M3_XIP_204C_TX_BASE};
	uint32_t base_address_rx[] = {JESDABC_M0_XIP_204C_RX_BASE,  JESDABC_M1_XIP_204C_RX_BASE,  JESDABC_M2_XIP_204C_RX_BASE,  JESDABC_M3_XIP_204C_RX_BASE};


	for(j=0; j<1; j++)
	{
		tx_gb_empty_st = read_reg_18a(base_address_tx[i] + JESD_XIP_204C_TX_MEM_TX_GEARBOX_EMPTY_STATUS_OFFSET, "JL_N_tx_gb_empty_st_REG");
		tx_gb_full_st = read_reg_18a(base_address_tx[i] + JESD_XIP_204C_TX_MEM_TX_GEARBOX_FULL_STATUS_OFFSET, "JL_N_tx_gb_full_st_REG");
	}

	printf("\n\n");
	printf("Before jesd enable value for JL_N_tx_gb_empty_st_REG --------is 0x%x \n", tx_gb_empty_st);
	printf("Before jesd enable value for JL_N_tx_gb_full_st_REG ---------is 0x%x \n", tx_gb_full_st);
	
	// JESD IP en 
	program_enable_registers();
	
	//enable sysref for jesd0/tx jesd
	
	system("frioPciWrite -F s5a3 -P 0x20000 0x06");//IP
	system("frioPciWrite -F s5a1 -P 0x20000 0x94");
	system("frioPciWrite -F s5b1 -P 0x20000 0x94");
	
	printf("After JESD_EN : SYSREF for JESD0 Done\n");
	//=================================
	//=================================
	uint32_t tx_gb_empty_reg = 0;
	uint32_t tx_gb_full_reg = 0;
	uint32_t rx_gb_empty_reg = 0;
	uint32_t rx_gb_full_reg = 0;
	uint32_t value28=0;
	uint32_t value32=0;
	uint32_t value36=0;
	uint32_t value37=0;
	i,j=0;
	/* uint32_t base_address_rx[] = {JESDABC_M0_XIP_204C_RX_BASE,  JESDABC_M1_XIP_204C_RX_BASE,  JESDABC_M2_XIP_204C_RX_BASE,  JESDABC_M3_XIP_204C_RX_BASE};
	uint32_t base_address_tx[] = {JESDABC_M0_XIP_204C_TX_BASE,  JESDABC_M1_XIP_204C_TX_BASE,  JESDABC_M2_XIP_204C_TX_BASE,  JESDABC_M3_XIP_204C_TX_BASE}; */
	// tx_gb_empty_reg = 0;
	// tx_gb_full_reg = 0;
	// rx_gb_empty_reg = 0;
	// rx_gb_full_reg = 0;
	printf("\n");
	printf("\n");
	for(i=0; i<1; i++)
	{
		tx_gb_empty_reg = read_reg_18a(base_address_tx[i] + JESD_XIP_204C_TX_MEM_TX_GEARBOX_EMPTY_STATUS_OFFSET, "JL_N_TX_GB_EMPTY_REG");
		tx_gb_full_reg = read_reg_18a(base_address_tx[i] + JESD_XIP_204C_TX_MEM_TX_GEARBOX_FULL_STATUS_OFFSET, "JL_N_TX_GB_FULL_REG");
	}
	for(j=0; j<1; j++)
	{
		//using JESDABC_M1_XIP_204C_RX_BASE to configure jesd1 for rx
		rx_gb_empty_reg = read_reg_18a(base_address_rx[j] + JESD_XIP_204C_RX_MEM_RX_GEARBOX_EMPTY_STATUS_OFFSET, "JL_N_RX_GB_EMPTY_REG");
		rx_gb_full_reg = read_reg_18a(base_address_rx[j] + JESD_XIP_204C_RX_MEM_RX_GEARBOX_FULL_STATUS_OFFSET, "JL_N_RX_GB_FULL_REG");
	}

	printf(" After SYSREF value for JL_N_TX_GB_EMPTY_REG --------is 0x%x \n", tx_gb_empty_reg);
	printf(" After SYSREF value for JL_N_TX_GB_FULL_REG ---------is 0x%x \n", tx_gb_full_reg);
	printf(" After SYSREF value for JL_N_RX_GB_EMPTY_REG --------is 0x%x \n", rx_gb_empty_reg);
	printf(" After SYSREF value for JL_N_RX_GB_FULL_REG ---------is 0x%x \n", rx_gb_full_reg);
	printf("\n");
	printf("\n");
	
	value28  = read_reg_18a(base_address_rx[0] + JESD_XIP_204C_RX_MEM_RX_SH_LOCK_STATUS_OFFSET, "JESD_XIP_RX_MEM_JL_SH_LOCK_STATUS");
	value32  = read_reg_18a(base_address_rx[0] + JESD_XIP_204C_RX_MEM_RX_EMB_LOCK_STATUS_OFFSET, "JESD_XIP_RX_MEM_JL_EMB_LOCK_STATUS");
	value36  = read_reg_18a(base_address_rx[0] + JESD_XIP_204C_RX_MEM_RX_SH_LOCK_LOSS_STATUS_OFFSET, "JESD_XIP_RX_MEM_JL_SH_LOCK_LOSS_STATUS");
	value37  = read_reg_18a(base_address_rx[0] + JESD_XIP_204C_RX_MEM_RX_EMB_LOCK_LOSS_STATUS_OFFSET, "JESD_XIP_RX_MEM_JL_SH_LOCK_LOSS_STATUS");
	
	printf("\n\n");
	printf("After SYSREF value of SH lock of Link0 is 0x%x \n",value28);
	printf("After SYSREF value of EMB lock of Link0 is 0x%x \n",value32);
	printf("After SYSREF value of SH lock loss of Link0 is 0x%x \n",value36);
	printf("After SYSREF value of EMB lock loss of Link0 is 0x%x \n",value37);
	//=================================	
}

void delay(unsigned int milliseconds)
{

    clock_t start = clock();

    while((clock() - start) * 1000 / CLOCKS_PER_SEC < milliseconds);
}

// JESD RX IP reg
int program_rx_ip_registers()
{
	int i=0;
	uint32_t base_address_rx[] = {JESDABC_M0_XIP_204C_RX_BASE,  JESDABC_M1_XIP_204C_RX_BASE,  JESDABC_M2_XIP_204C_RX_BASE,  JESDABC_M3_XIP_204C_RX_BASE};
	printf("JESD RX IP CONFIG : program_rx_ip_registers \n");
	//for(i=0; i<sizeof(base_address_rx) / sizeof(base_address_rx[0]); i++)
	for(i=0; i<1; i++)
	{ 
		write_read_expect_18a(base_address_rx[i]+JESD_XIP_204C_RX_MEM_RX_SUBCLASS_OFFSET, JESD_XIP_204C_RX_MEM_RX_SUBCLASS_REG_DEFAULT, 0x00000001, 0x00000001, JESD_XIP_204C_RX_MEM_RX_SUBCLASS_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_SUBCLASS_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_SUBCLASS_OFFSET");
		write_read_expect_18a(base_address_rx[i]+JESD_XIP_204C_RX_MEM_RX_FEC_OFFSET, JESD_XIP_204C_RX_MEM_RX_FEC_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_RX_MEM_RX_FEC_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_FEC_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_FEC_OFFSET");
		write_read_expect_18a(base_address_rx[i]+JESD_XIP_204C_RX_MEM_RX_CRC3_EN_OFFSET, JESD_XIP_204C_RX_MEM_RX_CRC3_EN_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_RX_MEM_RX_CRC3_EN_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_CRC3_EN_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_CRC3_EN_OFFSET");
		write_read_expect_18a(base_address_rx[i]+JESD_XIP_204C_RX_MEM_RX_CRC12_EN_OFFSET, JESD_XIP_204C_RX_MEM_RX_CRC12_EN_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_RX_MEM_RX_CRC12_EN_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_CRC12_EN_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_CRC12_EN_OFFSET");
		write_read_expect_18a(base_address_rx[i]+JESD_XIP_204C_RX_MEM_RX_BIT_ORDER_OFFSET, JESD_XIP_204C_RX_MEM_RX_BIT_ORDER_REG_DEFAULT, 0x00000003, 0x00000003, JESD_XIP_204C_RX_MEM_RX_BIT_ORDER_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_BIT_ORDER_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_BIT_ORDER_OFFSET");
		
		write_read_expect_18a(base_address_rx[i]+JESD_XIP_204C_RX_MEM_RX_E_OFFSET, JESD_XIP_204C_RX_MEM_RX_E_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_RX_MEM_RX_E_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_E_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_E_OFFSET");
		write_read_expect_18a(base_address_rx[i]+JESD_XIP_204C_RX_MEM_RX_CF_OFFSET, JESD_XIP_204C_RX_MEM_RX_CF_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_RX_MEM_RX_CF_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_CF_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_CF_OFFSET");
		write_read_expect_18a(base_address_rx[i]+JESD_XIP_204C_RX_MEM_RX_HD_OFFSET, JESD_XIP_204C_RX_MEM_RX_HD_REG_DEFAULT, 0x00000001, 0x00000001, JESD_XIP_204C_RX_MEM_RX_HD_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_HD_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_HD_OFFSET");
		write_read_expect_18a(base_address_rx[i]+JESD_XIP_204C_RX_MEM_RX_CMD_EN_OFFSET, JESD_XIP_204C_RX_MEM_RX_CMD_EN_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_RX_MEM_RX_CMD_EN_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_CMD_EN_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_CMD_EN_OFFSET");
		write_read_expect_18a(base_address_rx[i]+JESD_XIP_204C_RX_MEM_RX_CLK_RATIO_OFFSET, JESD_XIP_204C_RX_MEM_RX_CLK_RATIO_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_RX_MEM_RX_CLK_RATIO_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_CLK_RATIO_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_CLK_RATIO_OFFSET");
		write_read_expect_18a(base_address_rx[i]+JESD_XIP_204C_RX_MEM_RX_S_OFFSET, JESD_XIP_204C_RX_MEM_RX_S_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_RX_MEM_RX_S_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_S_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_S_OFFSET");
		
		write_read_expect_18a(base_address_rx[i]+JESD_XIP_204C_RX_MEM_RX_SONIF_OFFSET, JESD_XIP_204C_RX_MEM_RX_SONIF_REG_DEFAULT, 0x00000100, 0x00000100, JESD_XIP_204C_RX_MEM_RX_SONIF_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_SONIF_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_SONIF_OFFSET");
		write_read_expect_18a(base_address_rx[i]+JESD_XIP_204C_RX_MEM_RX_N_OFFSET, JESD_XIP_204C_RX_MEM_RX_N_REG_DEFAULT, 0x0000000f, 0x0000000f, JESD_XIP_204C_RX_MEM_RX_N_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_N_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_N_OFFSET");
		write_read_expect_18a(base_address_rx[i]+JESD_XIP_204C_RX_MEM_RX_NTOTAL_OFFSET, JESD_XIP_204C_RX_MEM_RX_NTOTAL_REG_DEFAULT, 0x0000000f, 0x0000000f, JESD_XIP_204C_RX_MEM_RX_NTOTAL_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_NTOTAL_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_NTOTAL_OFFSET");
		write_read_expect_18a(base_address_rx[i]+JESD_XIP_204C_RX_MEM_RX_CS_OFFSET, JESD_XIP_204C_RX_MEM_RX_CS_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_RX_MEM_RX_CS_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_CS_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_CS_OFFSET");
		
		write_read_expect_18a(base_address_rx[i]+JESD_XIP_204C_RX_MEM_RX_TL_TEST_MODE_OFFSET, JESD_XIP_204C_RX_MEM_RX_TL_TEST_MODE_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_RX_MEM_RX_TL_TEST_MODE_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_TL_TEST_MODE_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_TL_TEST_MODE_OFFSET");
		write_read_expect_18a(base_address_rx[i]+JESD_XIP_204C_RX_MEM_RX_SCR_OFFSET, JESD_XIP_204C_RX_MEM_RX_SCR_REG_DEFAULT, 0x00000001, 0x00000001, JESD_XIP_204C_RX_MEM_RX_SCR_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_SCR_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_SCR_OFFSET");
		
		printf("####JESD RX path - UC 5E 32G -LMFS -2-16-16-1 - IQ bandwidth -\n");
		write_read_expect_18a(JESDABC_M0_XIP_204C_RX_BASE+JESD_XIP_204C_RX_MEM_RX_L_OFFSET, JESD_XIP_204C_RX_MEM_RX_L_REG_DEFAULT, 0x00000001, 0x00000001, JESD_XIP_204C_RX_MEM_RX_L_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_L_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_L_OFFSET");
		write_read_expect_18a(JESDABC_M0_XIP_204C_RX_BASE+JESD_XIP_204C_RX_MEM_RX_M_OFFSET, JESD_XIP_204C_RX_MEM_RX_M_REG_DEFAULT, 0x0000000f, 0x0000000f, JESD_XIP_204C_RX_MEM_RX_M_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_M_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_M_OFFSET");
		write_read_expect_18a(JESDABC_M0_XIP_204C_RX_BASE+JESD_XIP_204C_RX_MEM_RX_F_OFFSET, JESD_XIP_204C_RX_MEM_RX_F_REG_DEFAULT, 0x0000000f, 0x0000000f, JESD_XIP_204C_RX_MEM_RX_F_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_F_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_F_OFFSET");

		write_read_expect_18a(JESDABC_M0_XIP_204C_RX_BASE+JESD_XIP_204C_RX_MEM_RX_THRESH_EMB_ERR_OFFSET, JESD_XIP_204C_RX_MEM_RX_THRESH_EMB_ERR_REG_DEFAULT, 0x00000009, 0x00000009, JESD_XIP_204C_RX_MEM_RX_THRESH_EMB_ERR_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_THRESH_EMB_ERR_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_THRESH_EMB_ERR_OFFSET");
		write_read_expect_18a(JESDABC_M0_XIP_204C_RX_BASE+JESD_XIP_204C_RX_MEM_RX_THRESH_SH_ERR_OFFSET, JESD_XIP_204C_RX_MEM_RX_THRESH_SH_ERR_REG_DEFAULT, 0x00000009, 0x00000009, JESD_XIP_204C_RX_MEM_RX_THRESH_SH_ERR_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_THRESH_SH_ERR_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_THRESH_SH_ERR_OFFSET");
   }
}	

// JESD RX glue reg
int program_rx_glue_registers()
{
	int i=0;
	uint32_t base_address_rx_glue[] = {JESDABC_M0_RX_GLUE_BASE,  JESDABC_M1_RX_GLUE_BASE,  JESDABC_M2_RX_GLUE_BASE,  JESDABC_M3_RX_GLUE_BASE};
	printf("JESD RX GLUE CONFIG : program_rx_glue_registers \n");
	//for(i=0; i<sizeof(base_address_rx_glue) / sizeof(base_address_rx_glue[0]); i++)
	for(i=0; i<1; i++)
	{ 
	   //enabling for 8 streams, 5/1/24
		printf("########JESD RX GLUE CONFIG : usecase-5E \n");
		write_read_expect_18a(base_address_rx_glue[i]+JESDABC_RX_GLUE_MEM_WR_MEM_TBL0_OFFSET, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_DEFAULT, 0x00000000, 0x00000000, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_RD_MASK, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_WR_MASK, "JESDABC_RX_GLUE_MEM_WR_MEM_TBL0_OFFSET");
		write_read_expect_18a(base_address_rx_glue[i]+JESDABC_RX_GLUE_MEM_WR_MEM_TBL1_OFFSET, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_DEFAULT, 0x00000040, 0x00000040, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_RD_MASK, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_WR_MASK, "JESDABC_RX_GLUE_MEM_WR_MEM_TBL1_OFFSET");
		write_read_expect_18a(base_address_rx_glue[i]+JESDABC_RX_GLUE_MEM_WR_MEM_TBL2_OFFSET, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_DEFAULT, 0x00000080, 0x00000080, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_RD_MASK, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_WR_MASK, "JESDABC_RX_GLUE_MEM_WR_MEM_TBL2_OFFSET");
		write_read_expect_18a(base_address_rx_glue[i]+JESDABC_RX_GLUE_MEM_WR_MEM_TBL3_OFFSET, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_DEFAULT, 0x000000c0, 0x000000c0, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_RD_MASK, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_WR_MASK, "JESDABC_RX_GLUE_MEM_WR_MEM_TBL3_OFFSET");
		write_read_expect_18a(base_address_rx_glue[i]+JESDABC_RX_GLUE_MEM_WR_MEM_TBL4_OFFSET, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_DEFAULT, 0x00000100, 0x00000100, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_RD_MASK, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_WR_MASK, "JESDABC_RX_GLUE_MEM_WR_MEM_TBL4_OFFSET");
		write_read_expect_18a(base_address_rx_glue[i]+JESDABC_RX_GLUE_MEM_WR_MEM_TBL5_OFFSET, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_DEFAULT, 0x00000140, 0x00000140, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_RD_MASK, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_WR_MASK, "JESDABC_RX_GLUE_MEM_WR_MEM_TBL5_OFFSET");
		write_read_expect_18a(base_address_rx_glue[i]+JESDABC_RX_GLUE_MEM_WR_MEM_TBL6_OFFSET, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_DEFAULT, 0x00000180, 0x00000180, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_RD_MASK, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_WR_MASK, "JESDABC_RX_GLUE_MEM_WR_MEM_TBL6_OFFSET");
		write_read_expect_18a(base_address_rx_glue[i]+JESDABC_RX_GLUE_MEM_WR_MEM_TBL7_OFFSET, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_DEFAULT, 0x000001c0, 0x000001c0, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_RD_MASK, JESDABC_RX_GLUE_MEM_WR_MEM_TBL_WR_MASK, "JESDABC_RX_GLUE_MEM_WR_MEM_TBL7_OFFSET");
		
		//enabling for 8 streams, 5/1/24
		write_read_expect_18a(base_address_rx_glue[i]+JESDABC_RX_GLUE_MEM_RD_MEM_TBL0_OFFSET, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_DEFAULT, 0x00000000, 0x00000000, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_RD_MASK, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_WR_MASK, "JESDABC_RX_GLUE_MEM_RD_MEM_TBL0_OFFSET");
		write_read_expect_18a(base_address_rx_glue[i]+JESDABC_RX_GLUE_MEM_RD_MEM_TBL1_OFFSET, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_DEFAULT, 0x00000240, 0x00000240, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_RD_MASK, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_WR_MASK, "JESDABC_RX_GLUE_MEM_RD_MEM_TBL1_OFFSET");
		write_read_expect_18a(base_address_rx_glue[i]+JESDABC_RX_GLUE_MEM_RD_MEM_TBL2_OFFSET, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_DEFAULT, 0x00000480, 0x00000480, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_RD_MASK, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_WR_MASK, "JESDABC_RX_GLUE_MEM_RD_MEM_TBL2_OFFSET");
		write_read_expect_18a(base_address_rx_glue[i]+JESDABC_RX_GLUE_MEM_RD_MEM_TBL3_OFFSET, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_DEFAULT, 0x000006c0, 0x000006c0, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_RD_MASK, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_WR_MASK, "JESDABC_RX_GLUE_MEM_RD_MEM_TBL3_OFFSET");
		write_read_expect_18a(base_address_rx_glue[i]+JESDABC_RX_GLUE_MEM_RD_MEM_TBL4_OFFSET, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_DEFAULT, 0x00000900, 0x00000900, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_RD_MASK, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_WR_MASK, "JESDABC_RX_GLUE_MEM_RD_MEM_TBL4_OFFSET");
		write_read_expect_18a(base_address_rx_glue[i]+JESDABC_RX_GLUE_MEM_RD_MEM_TBL5_OFFSET, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_DEFAULT, 0x00000b40, 0x00000b40, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_RD_MASK, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_WR_MASK, "JESDABC_RX_GLUE_MEM_RD_MEM_TBL5_OFFSET");
		write_read_expect_18a(base_address_rx_glue[i]+JESDABC_RX_GLUE_MEM_RD_MEM_TBL6_OFFSET, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_DEFAULT, 0x00000d80, 0x00000d80, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_RD_MASK, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_WR_MASK, "JESDABC_RX_GLUE_MEM_RD_MEM_TBL6_OFFSET");
		write_read_expect_18a(base_address_rx_glue[i]+JESDABC_RX_GLUE_MEM_RD_MEM_TBL7_OFFSET, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_DEFAULT, 0x00000fc0, 0x00000fc0, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_RD_MASK, JESDABC_RX_GLUE_MEM_RD_MEM_TBL_WR_MASK, "JESDABC_RX_GLUE_MEM_RD_MEM_TBL7_OFFSET");
		
		
		write_read_expect_18a(base_address_rx_glue[i]+JESDABC_RX_GLUE_MEM_RX_GLUE_SONI_OFFSET, JESDABC_RX_GLUE_MEM_RX_GLUE_SONI_DEFAULT, 0x00000001, 0x00000001, JESDABC_RX_GLUE_MEM_RX_GLUE_SONI_RD_MASK, JESDABC_RX_GLUE_MEM_RX_GLUE_SONI_WR_MASK, "JESDABC_RX_GLUE_MEM_RX_GLUE_SONI_OFFSET");
		write_read_expect_18a(base_address_rx_glue[i]+JESDABC_RX_GLUE_MEM_STRM_CFG_OFFSET, JESDABC_RX_GLUE_MEM_STRM_CFG_DEFAULT, 0x000000e8, 0x000000e8, JESDABC_RX_GLUE_MEM_STRM_CFG_RD_MASK, JESDABC_RX_GLUE_MEM_STRM_CFG_WR_MASK, "JESDABC_RX_GLUE_MEM_STRM_ID_EN");
		write_read_expect_18a(base_address_rx_glue[i]+JESDABC_RX_GLUE_MEM_STREAM_CFG_OFFSET, JESDABC_RX_GLUE_MEM_STREAM_CFG_DEFAULT, 0x0000003f, 0x0000003f, JESDABC_RX_GLUE_MEM_STREAM_CFG_RD_MASK, JESDABC_RX_GLUE_MEM_STREAM_CFG_WR_MASK, "JESDABC_RX_GLUE_MEM_STREAM_CFG_OFFSET");
	}
}
	
// JESD TX IP reg
int program_tx_ip_registers()
{
	int i=0;
	uint32_t base_address_tx[] = {JESDABC_M0_XIP_204C_TX_BASE,  JESDABC_M1_XIP_204C_TX_BASE,  JESDABC_M2_XIP_204C_TX_BASE,  JESDABC_M3_XIP_204C_TX_BASE};
	printf("JESD TX IP CONFIG : program_tx_ip_registers \n");
	//for(i=0; i<sizeof(base_address_tx) / sizeof(base_address_tx[0]); i++)
	for(i=0; i<1; i++)
	{ 
		// Common reg config for UC 
		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_SUBCLASS_OFFSET, JESD_XIP_204C_TX_MEM_TX_SUBCLASS_REG_DEFAULT, 0x00000001, 0x00000001, JESD_XIP_204C_TX_MEM_TX_SUBCLASS_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_SUBCLASS_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_SUBCLASS_OFFSET");
		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_FEC_OFFSET, JESD_XIP_204C_TX_MEM_TX_FEC_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_TX_MEM_TX_FEC_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_FEC_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_FEC_OFFSET");
		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_CRC3_EN_OFFSET, JESD_XIP_204C_TX_MEM_TX_CRC3_EN_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_TX_MEM_TX_CRC3_EN_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_CRC3_EN_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_CRC3_EN_OFFSET");
		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_CRC12_EN_OFFSET, JESD_XIP_204C_TX_MEM_TX_CRC12_EN_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_TX_MEM_TX_CRC12_EN_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_CRC12_EN_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_CRC12_EN_OFFSET");
		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_BIT_ORDER_OFFSET, JESD_XIP_204C_TX_MEM_TX_BIT_ORDER_REG_DEFAULT, 0x00000003, 0x00000003, JESD_XIP_204C_TX_MEM_TX_BIT_ORDER_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_BIT_ORDER_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_BIT_ORDER_OFFSET");

		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_E_OFFSET, JESD_XIP_204C_TX_MEM_TX_E_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_TX_MEM_TX_E_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_E_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_E_OFFSET");
		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_CF_OFFSET, JESD_XIP_204C_TX_MEM_TX_CF_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_TX_MEM_TX_CF_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_CF_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_CF_OFFSET");
		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_HD_OFFSET, JESD_XIP_204C_TX_MEM_TX_HD_REG_DEFAULT, 0x00000001, 0x00000001, JESD_XIP_204C_TX_MEM_TX_HD_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_HD_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_HD_OFFSET");

		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_CMD_EN_OFFSET, JESD_XIP_204C_TX_MEM_TX_CMD_EN_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_TX_MEM_TX_CMD_EN_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_CMD_EN_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_CMD_EN_OFFSET");
		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_CLK_RATIO_OFFSET, JESD_XIP_204C_TX_MEM_TX_CLK_RATIO_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_TX_MEM_TX_CLK_RATIO_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_CLK_RATIO_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_CLK_RATIO_OFFSET");

		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_S_OFFSET, JESD_XIP_204C_TX_MEM_TX_S_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_TX_MEM_TX_S_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_S_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_S_OFFSET");

		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_SONIF_OFFSET, JESD_XIP_204C_TX_MEM_TX_SONIF_REG_DEFAULT, 0x00000100, 0x00000100, JESD_XIP_204C_TX_MEM_TX_SONIF_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_SONIF_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_SONIF_OFFSET");
		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_N_OFFSET, JESD_XIP_204C_TX_MEM_TX_N_REG_DEFAULT, 0x0000000f, 0x0000000f, JESD_XIP_204C_TX_MEM_TX_N_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_N_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_N_OFFSET");
		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_NTOTAL_OFFSET, JESD_XIP_204C_TX_MEM_TX_NTOTAL_REG_DEFAULT, 0x0000000f, 0x0000000f, JESD_XIP_204C_TX_MEM_TX_NTOTAL_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_NTOTAL_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_NTOTAL_OFFSET");
		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_CS_OFFSET, JESD_XIP_204C_TX_MEM_TX_CS_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_TX_MEM_TX_CS_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_CS_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_CS_OFFSET");
		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_TL_TEST_MODE_OFFSET, JESD_XIP_204C_TX_MEM_TX_TL_TEST_MODE_REG_DEFAULT, 0x00000000, 0x00000000, JESD_XIP_204C_TX_MEM_TX_TL_TEST_MODE_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_TL_TEST_MODE_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_TL_TEST_MODE_OFFSET");

		printf("########JESD tx path - UC 5E -LMFS -2-16-16-1 \n");
		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_SAMPLE_REQ_OFFSET, JESD_XIP_204C_TX_MEM_TX_SAMPLE_REQ_REG_DEFAULT, 0x00000101, 0x00000101, JESD_XIP_204C_TX_MEM_TX_SAMPLE_REQ_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_SAMPLE_REQ_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_SAMPLE_REQ_OFFSET");

		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_L_OFFSET, JESD_XIP_204C_TX_MEM_TX_L_REG_DEFAULT, 0x00000001, 0x00000001, JESD_XIP_204C_TX_MEM_TX_L_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_L_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_L_OFFSET");
		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_M_OFFSET, JESD_XIP_204C_TX_MEM_TX_M_REG_DEFAULT, 0x0000000f, 0x0000000f, JESD_XIP_204C_TX_MEM_TX_M_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_M_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_M_OFFSET");
		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_F_OFFSET, JESD_XIP_204C_TX_MEM_TX_F_REG_DEFAULT, 0x0000000f, 0x0000000f, JESD_XIP_204C_TX_MEM_TX_F_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_F_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_F_OFFSET");

		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_TL_LATENCY_OFFSET, JESD_XIP_204C_TX_MEM_TX_TL_LATENCY_REG_DEFAULT, 0x0000000c, 0x0000000c, JESD_XIP_204C_TX_MEM_TX_TL_LATENCY_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_TL_LATENCY_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_TL_LATENCY_OFFSET");
		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_SCR_OFFSET, JESD_XIP_204C_TX_MEM_TX_SCR_REG_DEFAULT, 0x00000001, 0x00000001, JESD_XIP_204C_TX_MEM_TX_SCR_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_SCR_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_SCR_OFFSET");
	}
}

// JESD CMN CSR reg
int program_cmn_csr_registers()
{
	int i=0;
	uint32_t base_address_cmn[] = {JESDABC_M0_CMN_CSR_BASE,  JESDABC_M1_CMN_CSR_BASE,  JESDABC_M2_CMN_CSR_BASE,  JESDABC_M3_CMN_CSR_BASE};
	printf("JESD CMN CSR CONFIG : program_cmn_csr_registers \n");
	//for(i=0; i<sizeof(base_address_cmn) / sizeof(base_address_cmn[0]); i++)
	for(i=0; i<1; i++)
	{ 		
		printf("\n####### configuring cmn_csr for 5E\n");
		write_read_expect_18a(base_address_cmn[i]+JESDABC_CMN_CSR_MEM_TX_IP_CLK_CTRL_OFFSET, JESDABC_CMN_CSR_MEM_TX_IP_CLK_CTRL_DEFAULT, 0x00000001, 0x00000001, JESDABC_CMN_CSR_MEM_TX_IP_CLK_CTRL_RD_MASK, JESDABC_CMN_CSR_MEM_TX_IP_CLK_CTRL_WR_MASK, "JESDABC_CMN_CSR_MEM_TX_IP_CLK_CTRL_OFFSET");
		write_read_expect_18a(base_address_cmn[i]+JESDABC_CMN_CSR_MEM_RX_IP_CLK_CTRL_OFFSET, JESDABC_CMN_CSR_MEM_RX_IP_CLK_CTRL_DEFAULT, 0x00000001, 0x00000001, JESDABC_CMN_CSR_MEM_RX_IP_CLK_CTRL_RD_MASK, JESDABC_CMN_CSR_MEM_RX_IP_CLK_CTRL_WR_MASK, "JESDABC_CMN_CSR_MEM_RX_IP_CLK_CTRL_OFFSET");
	}
}

// JESD TX glue reg
int program_tx_glue_registers()
{
	int i=0;
	uint32_t base_address_tx_glue[] = {JESDABC_M0_TX_GLUE_BASE,  JESDABC_M1_TX_GLUE_BASE,  JESDABC_M2_TX_GLUE_BASE,  JESDABC_M3_TX_GLUE_BASE};
	printf("JESD TX GLUE CONFIG : program_tx_glue_registers \n");
	//for(i=0; i<sizeof(base_address_tx_glue) / sizeof(base_address_tx_glue[0]); i++)
	for(i=0; i<1; i++)	
	{ 		
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR0_OFFSET, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_DEFAULT, 0x00000000, 0x00000000, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_RD_MASK, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_WR_MASK, "JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR0_OFFSET");
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR1_OFFSET, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_DEFAULT, 0x00002000, 0x00002000, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_RD_MASK, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_WR_MASK, "JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR1_OFFSET");
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR2_OFFSET, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_DEFAULT, 0x00004000, 0x00004000, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_RD_MASK, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_WR_MASK, "JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR2_OFFSET");
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR3_OFFSET, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_DEFAULT, 0x00006000, 0x00006000, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_RD_MASK, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_WR_MASK, "JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR3_OFFSET");
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR4_OFFSET, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_DEFAULT, 0x00008000, 0x00008000, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_RD_MASK, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_WR_MASK, "JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR4_OFFSET");
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR5_OFFSET, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_DEFAULT, 0x0000a000, 0x0000a000, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_RD_MASK, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_WR_MASK, "JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR5_OFFSET");
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR6_OFFSET, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_DEFAULT, 0x0000c000, 0x0000c000, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_RD_MASK, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_WR_MASK, "JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR6_OFFSET");
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR7_OFFSET, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_DEFAULT, 0x0000e000, 0x0000e000, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_RD_MASK, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR_WR_MASK, "JESDABC_TX_GLUE_MEM_STRM_ID_MEM_ADDR7_OFFSET");
		
		//changing to 4kb per stream 0x00000fff
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE0_OFFSET, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_DEFAULT, 0x00001fff, 0x00001fff, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_RD_MASK, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_WR_MASK, "JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE0_OFFSET");
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE1_OFFSET, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_DEFAULT, 0x00001fff, 0x00001fff, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_RD_MASK, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_WR_MASK, "JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE1_OFFSET");
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE2_OFFSET, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_DEFAULT, 0x00001fff, 0x00001fff, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_RD_MASK, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_WR_MASK, "JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE2_OFFSET");
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE3_OFFSET, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_DEFAULT, 0x00001fff, 0x00001fff, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_RD_MASK, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_WR_MASK, "JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE3_OFFSET");
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE4_OFFSET, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_DEFAULT, 0x00001fff, 0x00001fff, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_RD_MASK, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_WR_MASK, "JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE4_OFFSET");
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE5_OFFSET, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_DEFAULT, 0x00001fff, 0x00001fff, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_RD_MASK, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_WR_MASK, "JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE5_OFFSET");
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE6_OFFSET, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_DEFAULT, 0x00001fff, 0x00001fff, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_RD_MASK, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_WR_MASK, "JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE6_OFFSET");
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE7_OFFSET, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_DEFAULT, 0x00001fff, 0x00001fff, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_RD_MASK, JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE_WR_MASK, "JESDABC_TX_GLUE_MEM_STRM_ID_MEM_SIZE7_OFFSET");
		
		// 8 stream changing to 1 memory blocks =4kb - 8*4 =32kb -> 0x1
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_STRM_MEM_INST_CNT_OFFSET, JESDABC_TX_GLUE_MEM_STRM_MEM_INST_CNT_DEFAULT, 0x00000002, 0x00000002, JESDABC_TX_GLUE_MEM_STRM_MEM_INST_CNT_RD_MASK, JESDABC_TX_GLUE_MEM_STRM_MEM_INST_CNT_WR_MASK, "JESDABC_TX_GLUE_MEM_STRM_MEM_INST_CNT_OFFSET");
		
		// 8 stream using 8 buffers - 0x000000ff 
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_TX_NUM_BUFFER_SETS_USED_OFFSET, JESDABC_TX_GLUE_MEM_TX_NUM_BUFFER_SETS_USED_DEFAULT, 0x000000ff, 0x000000ff, JESDABC_TX_GLUE_MEM_TX_NUM_BUFFER_SETS_USED_RD_MASK, JESDABC_TX_GLUE_MEM_TX_NUM_BUFFER_SETS_USED_WR_MASK, "JESDABC_TX_GLUE_MEM_TX_NUM_BUFFER_SETS_USED_OFFSET");
		
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_CONV_DP_CFG_OFFSET, JESDABC_TX_GLUE_MEM_CONV_DP_CFG_DEFAULT, 0x00000030, 0x00000030, JESDABC_TX_GLUE_MEM_CONV_DP_CFG_RD_MASK, JESDABC_TX_GLUE_MEM_CONV_DP_CFG_WR_MASK, "JESDABC_TX_GLUE_MEM_CONV_DP_CFG_OFFSET");
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_RD_CFG_OFFSET, JESDABC_TX_GLUE_MEM_RD_CFG_DEFAULT, 0x0000001f, 0x0000001f, JESDABC_TX_GLUE_MEM_RD_CFG_RD_MASK, JESDABC_TX_GLUE_MEM_RD_CFG_WR_MASK, "JESDABC_TX_GLUE_MEM_RD_CFG_OFFSET");

		// trig 0 - tsb level , trig1 - after trig 0 
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_TX_DATAPATH_EN_OFFSET, JESDABC_TX_GLUE_MEM_TX_DATAPATH_EN_REG_DEFAULT, 0x00000120, 0x00000120, JESDABC_TX_GLUE_MEM_TX_DATAPATH_EN_REG_RD_MASK, JESDABC_TX_GLUE_MEM_TX_DATAPATH_EN_REG_WR_MASK, "JESDABC_TX_GLUE_MEM_TX_DATAPATH_EN_OFFSET");
	
		//Each stream 0x80000fff -> fff trig fill level size -4kb,not triggering on half full (2kb), trigger en 
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_TX_TSB_TRIG_EN_OFFSET, JESDABC_TX_GLUE_MEM_TX_TSB_TRIG_EN_REG_DEFAULT, 0xc0000fff, 0xc0000fff, JESDABC_TX_GLUE_MEM_TX_TSB_TRIG_EN_REG_RD_MASK, JESDABC_TX_GLUE_MEM_TX_TSB_TRIG_EN_REG_WR_MASK, "JESDABC_TX_GLUE_MEM_TX_TSB_TRIG_EN_OFFSET");

		// cfg update - twice ? 
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_TX_CFG_UPD_OFFSET, JESDABC_TX_GLUE_MEM_TX_CFG_UPD_DEFAULT, 0x00000001, 0x00000001, JESDABC_TX_GLUE_MEM_TX_CFG_UPD_RD_MASK, JESDABC_TX_GLUE_MEM_TX_CFG_UPD_WR_MASK, "JESDABC_TX_GLUE_MEM_TX_CFG_UPD_OFFSET");
		
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_PHM_FOVR_EN_OFFSET, JESDABC_TX_GLUE_MEM_PHM_FOVR_EN_DEFAULT, 0x00000000, 0x00000000, JESDABC_TX_GLUE_MEM_PHM_FOVR_EN_RD_MASK, JESDABC_TX_GLUE_MEM_PHM_FOVR_EN_WR_MASK, "JESDABC_TX_GLUE_MEM_PHM_FOVR_EN_OFFSET");
		write_read_expect_18a(base_address_tx_glue[i]+JESDABC_TX_GLUE_MEM_TX_CFG_UPD_OFFSET, JESDABC_TX_GLUE_MEM_TX_CFG_UPD_DEFAULT, 0x00000001, 0x00000001, JESDABC_TX_GLUE_MEM_TX_CFG_UPD_RD_MASK, JESDABC_TX_GLUE_MEM_TX_CFG_UPD_WR_MASK, "JESDABC_TX_GLUE_MEM_TX_CFG_UPD_OFFSET");
	}
}

/*
// JESD BFN reg
int program_bfn_registers()
{
	printf("JESD BFN EVENT CONFIG : program_bfn_registers \n");
	for (core_number=0; core_number <= 1; core_number++)
	{
		write_read_expect_18a(JESD_JESDBFN_EVENTS_BASE + JESDABC_BFN_EVENTS_MEM_ISYNC_CTRL_OFFSET, core_number,JESD_JESDABC_BFN_EVENTS_ISYNC_CTRL,0x00000002,0x00000002,JESD_JESDABC_BFN_EVENTS_ISYNC_CTRL_RD_MASK,JESD_JESDABC_BFN_EVENTS_ISYNC_CTRL_WR_MASK,"JESD_JESDABC_BFN_EVENTS_ISYNC_CTRL");
		write_read_expect_18a(JESD_JESDBFN_EVENTS_BASE + JESDABC_BFN_EVENTS_MEM_ISYNC_TEN_MS_CNT_OFFSET, core_number,JESD_JESDABC_BFN_EVENTS_ISYNC_TEN_MS_CNT,0x00004000,0x00004000,JESD_JESDABC_BFN_EVENTS_ISYNC_TEN_MS_CNT_RD_MASK,JESD_JESDABC_BFN_EVENTS_ISYNC_TEN_MS_CNT_WR_MASK,"JESD_JESDABC_BFN_EVENTS_ISYNC_TEN_MS_CNT");

		for (i=0; i <= 7; i++)
		{
			write_read_expect_18a(JESD_JESDBFN_EVENTS_BASE + JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_CONFIG(i)_OFFSET, JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_CONFIG_DEFAULT,0x0000000d,0x0000000d,JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_CONFIG_RD_MASK,JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_CONFIG_WR_MASK,"JESD_JESDABC_BFN_EVENTS_BFNE_CONFIG");
			write_read_expect_18a(JESD_JESDBFN_EVENTS_BASE + JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_INCR(i)_OFFSET, JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_INCR_DEFAULT,0x00000400,0x00000400,JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_INCR_RD_MASK,JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_INCR_WR_MASK,"JESD_JESDABC_BFN_EVENTS_BFNE_INCR");
			write_read_expect_18a(JESD_JESDBFN_EVENTS_BASE + JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_START(i)_OFFSET, JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_START_DEFAULT,0x00000400,0x00000400,JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_START_RD_MASK,JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_START_WR_MASK,"JESD_JESDABC_BFN_EVENTS_BFNE_START");
			
			write_read_expect_18a(JESD_JESDBFN_EVENTS_BASE + JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_CONFIG(i)_OFFSET, JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_CONFIG_DEFAULT,0x0000000d,0x0000000d,JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_CONFIG_RD_MASK,JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_CONFIG_WR_MASK,"JESD_JESDABC_BFN_EVENTS_BFNE_CONFIG");
			write_read_expect_18a(JESD_JESDBFN_EVENTS_BASE + JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_INCR(i)_OFFSET, JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_INCR_DEFAULT,0x00000400,0x00000400,JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_INCR_RD_MASK,JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_INCR_WR_MASK,"JESD_JESDABC_BFN_EVENTS_BFNE_INCR");
			write_read_expect_18a(JESD_JESDBFN_EVENTS_BASE + JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_START(i)_OFFSET, JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_START_DEFAULT,0x000004c8,0x000004c8,JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_START_RD_MASK,JESDABC_BFN_EVENTS_MEM_BFN_EVENTS_BFNE_START_WR_MASK,"JESD_JESDABC_BFN_EVENTS_BFNE_START");
		}
	}
}
*/ 

// JESD enable reg
int program_enable_registers()
{
	int i,j = 0;
	uint32_t base_address_tx[] = {JESDABC_M0_XIP_204C_TX_BASE,  JESDABC_M1_XIP_204C_TX_BASE,  JESDABC_M2_XIP_204C_TX_BASE,  JESDABC_M3_XIP_204C_TX_BASE};
	uint32_t base_address_rx[] = {JESDABC_M0_XIP_204C_RX_BASE,  JESDABC_M1_XIP_204C_RX_BASE,  JESDABC_M2_XIP_204C_RX_BASE,  JESDABC_M3_XIP_204C_RX_BASE};
	printf("JESD ENABLE : program_enable_registers \n");
	//for(i=0; i<sizeof(base_address_tx) / sizeof(base_address_tx[0]); i++)
	for(i=0; i<1; i++)
	{ 
		write_read_expect_18a(base_address_tx[i]+JESD_XIP_204C_TX_MEM_TX_ENABLEMODULE_OFFSET, JESD_XIP_204C_TX_MEM_TX_ENABLEMODULE_REG_DEFAULT, 0x1, 0x1, JESD_XIP_204C_TX_MEM_TX_ENABLEMODULE_REG_RD_MASK, JESD_XIP_204C_TX_MEM_TX_ENABLEMODULE_REG_WR_MASK, "JESD_XIP_204C_TX_MEM_TX_ENABLEMODULE_OFFSET");
	}
	//for(j=0; i<sizeof(base_address_rx) / sizeof(base_address_rx[0]); j++)
	for(i=0; i<1; i++)
	{ 
		write_read_expect_18a(base_address_rx[i]+JESD_XIP_204C_RX_MEM_RX_ENABLEMODULE_OFFSET, JESD_XIP_204C_RX_MEM_RX_ENABLEMODULE_REG_DEFAULT, 0x1, 0x1, JESD_XIP_204C_RX_MEM_RX_ENABLEMODULE_REG_RD_MASK, JESD_XIP_204C_RX_MEM_RX_ENABLEMODULE_REG_WR_MASK, "JESD_XIP_204C_RX_MEM_RX_ENABLEMODULE_OFFSET");
	}
}

