# --------------------------------------------------------------------------------
# -- REQUIRED:  DO NOT REMOVE THESE STATEMENTS; DO NOT ALTER STATEMENT ORDER
# --------------------------------------------------------------------------------


#-- HWC Project Level Makefile for GEN_FILELIST
include ${WORKAREA}/project_tools/gen_filelist/Makefile


# -----------------------------------------------------------------------------------
# -- Locally Defined Makefile Targets 
# -----------------------------------------------------------------------------------
