# --------------------------------------------------------------------------------
# -- REQUIRED:  DO NOT REMOVE THESE STATEMENTS; DO NOT ALTER STATEMENT ORDER
# --------------------------------------------------------------------------------


#-- HWC Project Level Makefile forCPP 
include ${WORKAREA}/project_tools/verif/vcssim/Makefile
