/* INTEL CONFIDENTIAL
 *
 * Copyright 2024 Intel Corporation All Rights Reserved.
 *
 * The source code contained or described herein and all documents related
 * to the source code ("Material") are owned by Intel Corporation or its
 * suppliers or licensors. Title to the Material remains with Intel
 * Corporation or its suppliers and licensors. The Material contains trade
 * secrets and proprietary and confidential information of Intel or its
 * suppliers and licensors. The Material is protected by worldwide copyright
 * and trade secret laws and treaty provisions. No part of the Material
 * may be used, copied, reproduced, modified, published, uploaded, posted,
 * transmitted, distributed, or disclosed in any way without Intel's prior
 * express written permission.
 *
 * No license under any patent, copyright, trade secret or other
 * intellectual property right is granted to or conferred upon you by
 * disclosure or delivery of the Materials, either expressly, by
 * implication, inducement, estoppel or otherwise. Any license under such
 * intellectual property rights must be express and approved by Intel in
 * writing.
 *
 *****************************************************************************/

/**
 * this header file is generated by tool, any direct modification without going
 * through the table generation process will get lost
 */

#ifndef __AX_STATIC_DATA_DATA__
#define __AX_STATIC_DATA_DATA__

#include "ax_static_data_table.h"

// Initalization related constants for table ax_print_config_lut
#define AX_PRINT_CONFIG_LUT_VALID_ENTRY_NUM (4)
// 1x4x(1x32-bit)
#define AX_PRINT_CONFIG_LUT_DATA                                                            \
    {                                                                                       \
        [0].value = 0x23fc00, [1].value = 0x23fc00, [2].value = 0xbddd6200, [3].value = 0x0 \
    }

// Initalization related constants for table ax_jesd_rate_index_lut
#define AX_JESD_RATE_INDEX_LUT_VALID_ENTRY_NUM (96)
// 1x96x(1x32-bit)
#define AX_JESD_RATE_INDEX_LUT_DATA                                                                                                   \
    {                                                                                                                                 \
        [0].value = 0x40130, [1].value = 0x50240, [2].value = 0x30121, [3].value = 0x2241131, [4].value = 0x2251241,                  \
        [5].value = 0x2231122, [6].value = 0x2241232, [7].value = 0x5543132, [8].value = 0x2251442, [9].value = 0x5553242,            \
        [10].value = 0x5553454, [11].value = 0x4452443, [12].value = 0x4432224, [13].value = 0x5533124, [14].value = 0x2241434,       \
        [15].value = 0x4442434, [16].value = 0x5543234, [17].value = 0x5553444, [18].value = 0x4432225, [19].value = 0x4442435,       \
        [20].value = 0x7412106, [21].value = 0x5523116, [22].value = 0x5231426, [23].value = 0x7432426, [24].value = 0x5533226,       \
        [25].value = 0x5543436, [26].value = 0x7412107, [27].value = 0x7432427, [28].value = 0x8513108, [29].value = 0x5523218,       \
        [30].value = 0x5533428, [31].value = 0x7422419, [32].value = 0x551320a, [33].value = 0x552341a, [34].value = 0x741240b,       \
        [35].value = 0x851340c, [36].value = 0x0, [37].value = 0x0, [38].value = 0x0, [39].value = 0x0, [40].value = 0x81154243,      \
        [41].value = 0x84154444, [42].value = 0x82255244, [43].value = 0x84134125, [44].value = 0x84144235, [45].value = 0x84154445,  \
        [46].value = 0x87134226, [47].value = 0x87144436, [48].value = 0x85245236, [49].value = 0x85255446, [50].value = 0x86356446,  \
        [51].value = 0x87457346, [52].value = 0x87134227, [53].value = 0x87144437, [54].value = 0x87447227, [55].value = 0x81134428,  \
        [56].value = 0x88235228, [57].value = 0x86336228, [58].value = 0x88245438, [59].value = 0x86346438, [60].value = 0x87447338,  \
        [61].value = 0x87114109, [62].value = 0x87427119, [63].value = 0x87134429, [64].value = 0x87437229, [65].value = 0x8711420a,  \
        [66].value = 0x8712441a, [67].value = 0x8822521a, [68].value = 0x8632621a, [69].value = 0x8742721a, [70].value = 0x8523542a,  \
        [71].value = 0x8333642a, [72].value = 0x8743732a, [73].value = 0x8743742a, [74].value = 0x8711420b, [75].value = 0x8712441b,  \
        [76].value = 0x8742721b, [77].value = 0x8821520c, [78].value = 0x8631620c, [79].value = 0x8741720c, [80].value = 0x8822541c,  \
        [81].value = 0x8632641c, [82].value = 0x8742741c, [83].value = 0x8741720d, [84].value = 0x8821540e, [85].value = 0x0,         \
        [86].value = 0x0, [87].value = 0x0, [88].value = 0x0, [89].value = 0x0, [90].value = 0x0, [91].value = 0x0, [92].value = 0x0, \
        [93].value = 0x0, [94].value = 0x0, [95].value = 0x0                                                                          \
    }

// Initalization related constants for table ax_jesd_configuration_lut
#define AX_JESD_CONFIGURATION_LUT_VALID_ENTRY_NUM (96)
// 1x96x(1x32-bit)
#define AX_JESD_CONFIGURATION_LUT_DATA                                                                                                \
    {                                                                                                                                 \
        [0].value = 0x114b127c, [1].value = 0x114b127c, [2].value = 0xc49123c, [3].value = 0x114b127c, [4].value = 0x114b127c,        \
        [5].value = 0xc49123c, [6].value = 0xc49123c, [7].value = 0x114b127c, [8].value = 0xc49123c, [9].value = 0x114b127c,          \
        [10].value = 0xc4b22fc, [11].value = 0xc49123d, [12].value = 0xbd1122f, [13].value = 0xc49123c, [14].value = 0xb48121c,       \
        [15].value = 0xbd1122f, [16].value = 0xc49123c, [17].value = 0xc49123c, [18].value = 0xb48121d, [19].value = 0xb48121d,       \
        [20].value = 0xbd11417, [21].value = 0xb48121c, [22].value = 0x948140c, [23].value = 0xbd11417, [24].value = 0xb48121c,       \
        [25].value = 0xb48121c, [26].value = 0x948140d, [27].value = 0x948140d, [28].value = 0x948140c, [29].value = 0xc48220c,       \
        [30].value = 0xc48220c, [31].value = 0x7482405, [32].value = 0xa484204, [33].value = 0xa484204, [34].value = 0x6484501,       \
        [35].value = 0x6484500, [36].value = 0x0, [37].value = 0x0, [38].value = 0x0, [39].value = 0x0, [40].value = 0x1148127d,      \
        [41].value = 0xfd1145f, [42].value = 0x1148127c, [43].value = 0xc48143d, [44].value = 0xc48143d, [45].value = 0xc48143d,      \
        [46].value = 0xbd1182f, [47].value = 0xbd1182f, [48].value = 0xc48143c, [49].value = 0xc48143c, [50].value = 0xd61144c,       \
        [51].value = 0xfd1145d, [52].value = 0xb48181d, [53].value = 0xb48181d, [54].value = 0xc48143d, [55].value = 0xed10217,       \
        [56].value = 0xb48181c, [57].value = 0xd6124cc, [58].value = 0xb48181c, [59].value = 0xd6124cc, [60].value = 0xfd124dd,       \
        [61].value = 0xc48280d, [62].value = 0xc4824bd, [63].value = 0xc48280d, [64].value = 0xc4824bd, [65].value = 0xbd1480b,       \
        [66].value = 0xbd1480b, [67].value = 0xc48280c, [68].value = 0xd614410, [69].value = 0xed14417, [70].value = 0xc48440c,       \
        [71].value = 0xd610210, [72].value = 0xed14415, [73].value = 0xed14417, [74].value = 0xa484805, [75].value = 0xa484805,       \
        [76].value = 0xc48440d, [77].value = 0xa484804, [78].value = 0xd610490, [79].value = 0xbd1040b, [80].value = 0xa484804,       \
        [81].value = 0xd610490, [82].value = 0xbd1040b, [83].value = 0xa480405, [84].value = 0x9480900, [85].value = 0x0,             \
        [86].value = 0x0, [87].value = 0x0, [88].value = 0x0, [89].value = 0x0, [90].value = 0x0, [91].value = 0x0, [92].value = 0x0, \
        [93].value = 0x0, [94].value = 0x0, [95].value = 0x0                                                                          \
    }

// Initalization related constants for table ax_jesd_comp_param_lut
#define AX_JESD_COMP_PARAM_VALID_ENTRY_NUM (5)
// 1x5x(35x32-bit)
#define AX_JESD_COMP_PARAM_LUT_DATA                                                                                                 \
    {                                                                                                                               \
        [0].value = {0xbbc020af, 0x3000200, 0x1f3f4d36, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18,                       \
                     0x19,       0x1a,      0x28,       0x29, 0x2a, 0x1f, 0x0,  0x1,  0x2,  0x3,  0x4,  0x5,                        \
                     0x6,        0x7,       0x8,        0x9,  0xa,  0x20, 0x21, 0x22, 0xf,  0x25, 0x2f},                            \
        [1].value = {0xbc70306f, 0x1000200, 0x1f3f4936, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x28, 0x29,                       \
                     0x2a,       0x2b,      0x1f,       0x0,  0x1,  0x2,  0x3,  0x4,  0x5,  0x6,  0x20, 0x21,                       \
                     0x22,       0x23,      0xf,        0x25, 0x25, 0x25, 0x25, 0x25, 0x25, 0x25, 0x25},                            \
        [2].value =                                                                                                                 \
            {0xa382007f, 0x100, 0x1f3f4a35, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x28, 0x29, 0x2a, 0x1f, 0x0,  0x1, 0x2, \
             0x3,        0x4,   0x5,        0x6,  0x7,  0x20, 0x21, 0x22, 0xf,  0x25, 0x25, 0x25, 0x25, 0x25, 0x25, 0x25, 0x25},    \
        [3].value = {0x9bd000a7, 0x5000200, 0x7f004c26, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18,                       \
                     0x19,       0x1a,      0x1e,       0x28, 0x29, 0x2a, 0x0,  0x1,  0x2,  0x3,  0x4,  0x5,                        \
                     0x6,        0x7,       0x8,        0x9,  0xa,  0xe,  0x20, 0x21, 0x22, 0x25, 0x1f},                            \
        [4].value = {                                                                                                               \
            0x94803067,                                                                                                             \
            0x5000200,                                                                                                              \
            0x1f004826,                                                                                                             \
            0x10,                                                                                                                   \
            0x11,                                                                                                                   \
            0x12,                                                                                                                   \
            0x13,                                                                                                                   \
            0x14,                                                                                                                   \
            0x15,                                                                                                                   \
            0x16,                                                                                                                   \
            0x1f,                                                                                                                   \
            0x28,                                                                                                                   \
            0x29,                                                                                                                   \
            0x2a,                                                                                                                   \
            0x2b,                                                                                                                   \
            0x0,                                                                                                                    \
            0x1,                                                                                                                    \
            0x2,                                                                                                                    \
            0x3,                                                                                                                    \
            0x4,                                                                                                                    \
            0x5,                                                                                                                    \
            0x6,                                                                                                                    \
            0xf,                                                                                                                    \
            0x20,                                                                                                                   \
            0x21,                                                                                                                   \
            0x22,                                                                                                                   \
            0x23,                                                                                                                   \
            0x25,                                                                                                                   \
            0x25,                                                                                                                   \
            0x25,                                                                                                                   \
            0x25,                                                                                                                   \
            0x25,                                                                                                                   \
            0x25,                                                                                                                   \
            0x25,                                                                                                                   \
            0x25                                                                                                                    \
        }                                                                                                                           \
    }

// Initalization related constants for table ax_jesd_input_param_lut
// 1x1x(1x32-bit)
#define AX_JESD_INPUT_PARAM_LUT_DATA \
    {                                \
        [0].value = 0x0              \
    }

// Initalization related constants for table ax_jesd_decomp_param_lut
#define AX_JESD_COMP_PARAM_LUT_VALID_ENTRY_NUM (4)
// 1x4x(42x32-bit)
#define AX_JESD_DECOMP_PARAM_LUT_DATA                                                                             \
    {                                                                                                             \
        [0].value = {0x4481, 0x1f001025, 0x0,  0x1,  0x2,  0x3,  0x4, 0x5, 0x6,  0x7,  0x7,  0x7,  0x7,  0x7,     \
                     0x7,    0x7,        0x7,  0x7,  0xc,  0xd,  0xe, 0xf, 0x10, 0x11, 0x12, 0x13, 0x13, 0x13,    \
                     0x13,   0x13,       0x13, 0x13, 0x13, 0x13, 0x8, 0x9, 0xa,  0xb,  0x14, 0x15, 0x16, 0x17},   \
        [1].value = {0x6479, 0x1f3f1035, 0x0,  0x1,  0x2,  0x3,  0x4, 0x5, 0x6,  0x20, 0x21, 0x21, 0x21, 0x21,    \
                     0x21,   0x21,       0x21, 0xb,  0xc,  0xd,  0xe, 0xf, 0x10, 0x11, 0x12, 0x20, 0x21, 0x21,    \
                     0x21,   0x21,       0x21, 0x21, 0x21, 0x17, 0x7, 0x8, 0x9,  0xa,  0x13, 0x14, 0x15, 0x16},   \
        [2].value = {0x2499, 0x1f001015, 0x0,  0x1,  0x2,  0x3,  0x4,  0x5,  0x6,  0x7,  0x8,  0x21, 0x21, 0x21,  \
                     0x21,   0x21,       0x21, 0x9,  0xa,  0xb,  0xc,  0xd,  0xe,  0xf,  0x10, 0x11, 0x12, 0x21,  \
                     0x21,   0x21,       0x21, 0x21, 0x21, 0x13, 0x14, 0x15, 0x16, 0x17, 0x14, 0x15, 0x16, 0x17}, \
        [3].value = {                                                                                             \
            0x4a1,                                                                                                \
            0x1f001005,                                                                                           \
            0x0,                                                                                                  \
            0x1,                                                                                                  \
            0x2,                                                                                                  \
            0x3,                                                                                                  \
            0x4,                                                                                                  \
            0x5,                                                                                                  \
            0x6,                                                                                                  \
            0x7,                                                                                                  \
            0x8,                                                                                                  \
            0x9,                                                                                                  \
            0x9,                                                                                                  \
            0x9,                                                                                                  \
            0x9,                                                                                                  \
            0x9,                                                                                                  \
            0x9,                                                                                                  \
            0x9,                                                                                                  \
            0xa,                                                                                                  \
            0xb,                                                                                                  \
            0xc,                                                                                                  \
            0xd,                                                                                                  \
            0xe,                                                                                                  \
            0xf,                                                                                                  \
            0x10,                                                                                                 \
            0x11,                                                                                                 \
            0x12,                                                                                                 \
            0x13,                                                                                                 \
            0x13,                                                                                                 \
            0x13,                                                                                                 \
            0x13,                                                                                                 \
            0x13,                                                                                                 \
            0x13,                                                                                                 \
            0x13,                                                                                                 \
            0x14,                                                                                                 \
            0x15,                                                                                                 \
            0x16,                                                                                                 \
            0x17,                                                                                                 \
            0x14,                                                                                                 \
            0x15,                                                                                                 \
            0x16,                                                                                                 \
            0x17                                                                                                  \
        }                                                                                                         \
    }

// Initalization related constants for table ax_bfn_config_lut
// 1x1x(1x8-bit)
#define AX_BFN_CONFIG_LUT_DATA \
    {                          \
        [0].value = 0x7        \
    }

// Initalization related constants for table ax_bfn_selfsync_lut
#define AX_BFN_SELFSYNC_LUT_VALID_ENTRY_NUM (2)
// 1x2x(1x32-bit)
#define AX_BFN_SELFSYNC_LUT_DATA             \
    {                                        \
        [0].value = 0x7c2, [1].value = 0xb68 \
    }

#endif // __AX_STATIC_DATA_DATA__
