/* INTEL CONFIDENTIAL
 *
 * Copyright 2024 Intel Corporation All Rights Reserved.
 *
 * The source code contained or described herein and all documents related
 * to the source code ("Material") are owned by Intel Corporation or its
 * suppliers or licensors. Title to the Material remains with Intel
 * Corporation or its suppliers and licensors. The Material contains trade
 * secrets and proprietary and confidential information of Intel or its
 * suppliers and licensors. The Material is protected by worldwide copyright
 * and trade secret laws and treaty provisions. No part of the Material
 * may be used, copied, reproduced, modified, published, uploaded, posted,
 * transmitted, distributed, or disclosed in any way without Intel's prior
 * express written permission.
 *
 * No license under any patent, copyright, trade secret or other
 * intellectual property right is granted to or conferred upon you by
 * disclosure or delivery of the Materials, either expressly, by
 * implication, inducement, estoppel or otherwise. Any license under such
 * intellectual property rights must be express and approved by Intel in
 * writing.
 *
 *****************************************************************************/

/**
 * this header file is generated by tool, any direct modification without going
 * through the table generation process will get lost
 */

#ifndef __AX_STATIC_DATA_CONST__
#define __AX_STATIC_DATA_CONST__

// Table size definition for 1D table: ax_print_config_lut[4]
#define AX_PRINT_CONFIG_LUT_MAX_ENTRY_NUM (4)

// Table size definition for 1D table: ax_jesd_rate_index_lut[96]
#define AX_JESD_RATE_INDEX_LUT_MAX_ENTRY_NUM (96)

// Table size definition for 1D table: ax_jesd_configuration_lut[96]
#define AX_JESD_CONFIGURATION_LUT_MAX_ENTRY_NUM (96)

// Table size definition for 1D table: ax_jesd_comp_param_lut[5]
#define AX_JESD_COMP_PARAM_LUT_MAX_ENTRY_NUM (5)

// Table size definition for 1D table: ax_jesd_input_param_lut[1]
#define AX_JESD_INPUT_PARAM_LUT_MAX_ENTRY_NUM (1)

// Table size definition for 1D table: ax_jesd_decomp_param_lut[4]
#define AX_JESD_DECOMP_PARAM_LUT_MAX_ENTRY_NUM (4)

// Table size definition for 1D table: ax_bfn_config_lut[1]
#define AX_BFN_CONFIG_LUT_MAX_ENTRY_NUM (1)

// Table size definition for 1D table: ax_bfn_selfsync_lut[2]
#define AX_BFN_SELFSYNC_LUT_MAX_ENTRY_NUM (2)

#endif // __AX_STATIC_DATA_CONST__
