/* INTEL CONFIDENTIAL
 *
 * Copyright 2024 Intel Corporation All Rights Reserved.
 *
 * The source code contained or described herein and all documents related
 * to the source code ("Material") are owned by Intel Corporation or its
 * suppliers or licensors. Title to the Material remains with Intel
 * Corporation or its suppliers and licensors. The Material contains trade
 * secrets and proprietary and confidential information of Intel or its
 * suppliers and licensors. The Material is protected by worldwide copyright
 * and trade secret laws and treaty provisions. No part of the Material
 * may be used, copied, reproduced, modified, published, uploaded, posted,
 * transmitted, distributed, or disclosed in any way without Intel's prior
 * express written permission.
 *
 * No license under any patent, copyright, trade secret or other
 * intellectual property right is granted to or conferred upon you by
 * disclosure or delivery of the Materials, either expressly, by
 * implication, inducement, estoppel or otherwise. Any license under such
 * intellectual property rights must be express and approved by Intel in
 * writing.
 *
 *****************************************************************************/

/**
 * this header file is generated by tool, any direct modification without going
 * through the table generation process will get lost
 */

#ifndef __COM_STATIC_DATA_DATA__
#define __COM_STATIC_DATA_DATA__

#include "com_static_data_table.h"

// Initalization related constants for table com_fw_config_lut
// 1x1x(1x32-bit)
#define COM_FW_CONFIG_LUT_DATA \
    {                          \
        [0].value = 0x64002005 \
    }

// Initalization related constants for table com_trax_addr_config_lut
// 1x1x(2x32-bit)
#define COM_TRAX_ADDR_CONFIG_LUT_DATA \
    {                                 \
        [0].value = { 0x10000, 0x0 }  \
    }

// Initalization related constants for table com_drf_rate_conf_lut
#define DRF_RATE_CONF_VALID_ENTRY_NUM (129)
// 1x129x(1x32-bit)
#define COM_DRF_RATE_CONF_LUT_DATA                                                                                                   \
    {                                                                                                                                \
        [0].value = 0x18c1004, [1].value = 0x21d0008, [2].value = 0x1845003, [3].value = 0x31c1014, [4].value = 0x21c100d,           \
        [5].value = 0x43d0018, [6].value = 0x30c5013, [7].value = 0x63c1024, [8].value = 0x43c101d, [9].value = 0x7d0028,            \
        [10].value = 0x61c5023, [11].value = 0x7c102d, [12].value = 0x18d0044, [13].value = 0x20f0048, [14].value = 0x18c1043,       \
        [15].value = 0x31d0054, [16].value = 0x21d004d, [17].value = 0x41f0058, [18].value = 0x31c1053, [19].value = 0x63d0064,      \
        [20].value = 0x43d005d, [21].value = 0x3f0068, [22].value = 0x63c1063, [23].value = 0x7d006d, [24].value = 0x1841084,        \
        [25].value = 0x20d0088, [26].value = 0x1805083, [27].value = 0x30c1094, [28].value = 0x20c108d, [29].value = 0x41d0098,      \
        [30].value = 0x3045093, [31].value = 0x61c10a4, [32].value = 0x41c109d, [33].value = 0x3d00a8, [34].value = 0x60c50a3,       \
        [35].value = 0x3c10ad, [36].value = 0x18500c4, [37].value = 0x20700c8, [38].value = 0x18410c3, [39].value = 0x30d00d4,       \
        [40].value = 0x20d00cd, [41].value = 0x40f00d8, [42].value = 0x30c10d3, [43].value = 0x61d00e4, [44].value = 0x41d00dd,      \
        [45].value = 0x1f00e8, [46].value = 0x61c10e3, [47].value = 0x3d00ed, [48].value = 0x1801104, [49].value = 0x2050108,        \
        [50].value = 0x180d103, [51].value = 0x3041114, [52].value = 0x204110d, [53].value = 0x40d0118, [54].value = 0x3005113,      \
        [55].value = 0x60c1124, [56].value = 0x40c111d, [57].value = 0x1d0128, [58].value = 0x6045123, [59].value = 0x1c112d,        \
        [60].value = 0x1810144, [61].value = 0x2030148, [62].value = 0x1801143, [63].value = 0x3050154, [64].value = 0x205014d,      \
        [65].value = 0x4070158, [66].value = 0x3041153, [67].value = 0x60d0164, [68].value = 0x40d015d, [69].value = 0xf0168,        \
        [70].value = 0x60c1163, [71].value = 0x1d016d, [72].value = 0x1803184, [73].value = 0x2010188, [74].value = 0x180f183,       \
        [75].value = 0x3001194, [76].value = 0x200118d, [77].value = 0x4050198, [78].value = 0x300d193, [79].value = 0x60411a4,      \
        [80].value = 0x404119d, [81].value = 0xd01a8, [82].value = 0x60051a3, [83].value = 0xc11ad, [84].value = 0x18001c4,          \
        [85].value = 0x18001c3, [86].value = 0x30101d4, [87].value = 0x20101cd, [88].value = 0x40301d8, [89].value = 0x30011d3,      \
        [90].value = 0x60501e4, [91].value = 0x40501dd, [92].value = 0x701e8, [93].value = 0x60411e3, [94].value = 0xd01ed,          \
        [95].value = 0x2000208, [96].value = 0x3003214, [97].value = 0x200320d, [98].value = 0x4010218, [99].value = 0x300f213,      \
        [100].value = 0x6001224, [101].value = 0x400121d, [102].value = 0x50228, [103].value = 0x6007223, [104].value = 0x4122d,     \
        [105].value = 0x3000254, [106].value = 0x200024d, [107].value = 0x3003253, [108].value = 0x6010264, [109].value = 0x401025d, \
        [110].value = 0x6001263, [111].value = 0x5026d, [112].value = 0x4000298, [113].value = 0x60032a4, [114].value = 0x400329d,   \
        [115].value = 0x102a8, [116].value = 0x600f2a3, [117].value = 0x12ad, [118].value = 0x30002d3, [119].value = 0x60002e4,      \
        [120].value = 0x60032e3, [121].value = 0x102ed, [122].value = 0x1800d44, [123].value = 0x2000d88, [124].value = 0x3000dd4,   \
        [125].value = 0x2000dcd, [126].value = 0x4000e18, [127].value = 0x6000e64, [128].value = 0x4000e5d                           \
    }

// Initalization related constants for table com_vha_rate_conf_lut
#define VHA_RATE_CONF_VALID_ENTRY_NUM (11)
// 1x11x(1x16-bit)
#define COM_VHA_RATE_CONF_LUT_DATA                                                                                              \
    {                                                                                                                           \
        [0].value = 0x1823, [1].value = 0x4c37, [2].value = 0x2cb3, [3].value = 0x8d31, [4].value = 0x504f, [5].value = 0x30c7, \
        [6].value = 0x9143, [7].value = 0x51c1, [8].value = 0x34df, [9].value = 0x9557, [10].value = 0x55d3                     \
    }

// Initalization related constants for table com_vha_if_wm_lut
#define TX_VHA_IF_WM_F_1G                   (0)
#define TX_VHA_IF_WM_F_1G_VALID_ENTRY_NUM   (6)
#define TX_VHA_IF_WM_F_1P5G                 (1)
#define TX_VHA_IF_WM_F_1P5G_VALID_ENTRY_NUM (6)
// 2x6x(1x16-bit)
#define COM_VHA_IF_WM_LUT_DATA                                                                                                   \
    {                                                                                                                            \
        [TX_VHA_IF_WM_F_1G] =                                                                                                    \
            {[0].value = 0x408, [1].value = 0x810, [2].value = 0x1020, [3].value = 0x2040, [4].value = 0x4080, [5].value = 0x0}, \
        [TX_VHA_IF_WM_F_1P5G] = {                                                                                                \
            [0].value = 0x60c,                                                                                                   \
            [1].value = 0xc18,                                                                                                   \
            [2].value = 0x1830,                                                                                                  \
            [3].value = 0x3060,                                                                                                  \
            [4].value = 0x60c0,                                                                                                  \
            [5].value = 0x4080                                                                                                   \
        }                                                                                                                        \
    }

// Initalization related constants for table com_vex_hostid_lut
#define VEX_HOSTID_LUT_VALID_ENTRY_NUM (8)
// 1x8x(1x32-bit)
#define COM_VEX_HOSTID_LUT_DATA                                                                                            \
    {                                                                                                                      \
        [0].value = 0x204a020, [1].value = 0x225a862, [2].value = 0x246b0a4, [3].value = 0x267b8e6, [4].value = 0x21ce230, \
        [5].value = 0x23dea72, [6].value = 0x25ef2b4, [7].value = 0x27ffaf6                                                \
    }

// Initalization related constants for table com_v2d_hostid_lut
#define V2D_HOSTID_LUT_VALID_ENTRY_NUM (8)
// 1x8x(1x32-bit)
#define COM_V2D_HOSTID_LUT_DATA                                                                                            \
    {                                                                                                                      \
        [0].value = 0x93223c6, [1].value = 0x9f3a6cc, [2].value = 0xab529d2, [3].value = 0xb76acd8, [4].value = 0xc382fde, \
        [5].value = 0xcf9b2e4, [6].value = 0xdbb35ea, [7].value = 0xe7cb8f0                                                \
    }

// Initalization related constants for table com_vha_hostid_lut
#define VHA_HOSTID_LUT_VALID_ENTRY_NUM (8)
// 1x8x(1x16-bit)
#define COM_VHA_HOSTID_LUT_DATA                                                                                                 \
    {                                                                                                                           \
        [0].value = 0x22c4, [1].value = 0x25ca, [2].value = 0x28d0, [3].value = 0x2bd6, [4].value = 0x2edc, [5].value = 0x31e2, \
        [6].value = 0x34e8, [7].value = 0x37ee                                                                                  \
    }

// Initalization related constants for table com_rxfb_hostid_lut
#define RXFB_HOSTID_LUT_VALID_ENTRY_NUM (2)
// 1x2x(1x16-bit)
#define COM_RXFB_HOSTID_LUT_DATA               \
    {                                          \
        [0].value = 0x3af4, [1].value = 0x3c77 \
    }

// Initalization related constants for table com_jesd_hostid_lut
#define JESD_HOSTID_LUT_VALID_ENTRY_NUM (4)
// 1x4x(1x8-bit)
#define COM_JESD_HOSTID_LUT_DATA                                               \
    {                                                                          \
        [0].value = 0x40, [1].value = 0x41, [2].value = 0x42, [3].value = 0x43 \
    }

// Initalization related constants for table com_v2d_strm_cfg_lut
#define VEX_ASSIGNMENT_CFG_VALID_ENTRY_NUM (2)
// 1x2x(1x16-bit)
#define COM_V2D_STRM_CFG_LUT_DATA              \
    {                                          \
        [0].value = 0x1001, [1].value = 0x1208 \
    }

// Initalization related constants for table com_v2d_strm_buf_lut
#define VEX_BLK_SZ_P5US                 (0)
#define VEX_BLK_SZ_P5US_VALID_ENTRY_NUM (12)
#define VEX_BLK_SZ_1US                  (1)
#define VEX_BLK_SZ_1US_VALID_ENTRY_NUM  (12)
// 2x12x(1x32-bit)
#define COM_V2D_STRM_BUF_LUT_DATA                                                                                   \
    {                                                                                                               \
        [VEX_BLK_SZ_P5US] = {[0].value = 0x1007,  [1].value = 0x180b,  [2].value = 0x200f,   [3].value = 0x3017,    \
                             [4].value = 0x401f,  [5].value = 0x602f,  [6].value = 0x803f,   [7].value = 0xc05f,    \
                             [8].value = 0x1007f, [9].value = 0x180bf, [10].value = 0x200ff, [11].value = 0x3017f}, \
        [VEX_BLK_SZ_1US] = {                                                                                        \
            [0].value = 0x200f,                                                                                     \
            [1].value = 0x3017,                                                                                     \
            [2].value = 0x401f,                                                                                     \
            [3].value = 0x602f,                                                                                     \
            [4].value = 0x803f,                                                                                     \
            [5].value = 0xc05f,                                                                                     \
            [6].value = 0x1007f,                                                                                    \
            [7].value = 0x180bf,                                                                                    \
            [8].value = 0x200ff,                                                                                    \
            [9].value = 0x3017f,                                                                                    \
            [10].value = 0x401ff,                                                                                   \
            [11].value = 0x602ff                                                                                    \
        }                                                                                                           \
    }

#endif // __COM_STATIC_DATA_DATA__
