/* INTEL CONFIDENTIAL
 *
 * Copyright 2024 Intel Corporation All Rights Reserved.
 *
 * The source code contained or described herein and all documents related
 * to the source code ("Material") are owned by Intel Corporation or its
 * suppliers or licensors. Title to the Material remains with Intel
 * Corporation or its suppliers and licensors. The Material contains trade
 * secrets and proprietary and confidential information of Intel or its
 * suppliers and licensors. The Material is protected by worldwide copyright
 * and trade secret laws and treaty provisions. No part of the Material
 * may be used, copied, reproduced, modified, published, uploaded, posted,
 * transmitted, distributed, or disclosed in any way without Intel's prior
 * express written permission.
 *
 * No license under any patent, copyright, trade secret or other
 * intellectual property right is granted to or conferred upon you by
 * disclosure or delivery of the Materials, either expressly, by
 * implication, inducement, estoppel or otherwise. Any license under such
 * intellectual property rights must be express and approved by Intel in
 * writing.
 *
 *****************************************************************************/

/**
 * this header file is generated by tool, any direct modification without going
 * through the table generation process will get lost
 */

#ifndef __COM_STATIC_DATA_CONST__
#define __COM_STATIC_DATA_CONST__

// Table size definition for 1D table: com_fw_config_lut[1]
#define COM_FW_CONFIG_LUT_MAX_ENTRY_NUM (1)

// Table size definition for 1D table: com_trax_addr_config_lut[1]
#define COM_TRAX_ADDR_CONFIG_LUT_MAX_ENTRY_NUM (1)

// Table size definition for 1D table: com_drf_rate_conf_lut[129]
#define COM_DRF_RATE_CONF_LUT_MAX_ENTRY_NUM (129)

// Table size definition for 1D table: com_vha_rate_conf_lut[11]
#define COM_VHA_RATE_CONF_LUT_MAX_ENTRY_NUM (11)

// Table size definition for 2D table: com_vha_if_wm_lut[2][6]
#define COM_VHA_IF_WM_LUT_SUB_TBL_NUM   (2)
#define COM_VHA_IF_WM_LUT_MAX_ENTRY_NUM (6)

// Table size definition for 1D table: com_vex_hostid_lut[8]
#define COM_VEX_HOSTID_LUT_MAX_ENTRY_NUM (8)

// Table size definition for 1D table: com_v2d_hostid_lut[8]
#define COM_V2D_HOSTID_LUT_MAX_ENTRY_NUM (8)

// Table size definition for 1D table: com_vha_hostid_lut[8]
#define COM_VHA_HOSTID_LUT_MAX_ENTRY_NUM (8)

// Table size definition for 1D table: com_rxfb_hostid_lut[2]
#define COM_RXFB_HOSTID_LUT_MAX_ENTRY_NUM (2)

// Table size definition for 1D table: com_jesd_hostid_lut[4]
#define COM_JESD_HOSTID_LUT_MAX_ENTRY_NUM (4)

// Table size definition for 1D table: com_v2d_strm_cfg_lut[2]
#define COM_V2D_STRM_CFG_LUT_MAX_ENTRY_NUM (2)

// Table size definition for 2D table: com_v2d_strm_buf_lut[2][12]
#define COM_V2D_STRM_BUF_LUT_SUB_TBL_NUM   (2)
#define COM_V2D_STRM_BUF_LUT_MAX_ENTRY_NUM (12)

#endif // __COM_STATIC_DATA_CONST__
