/* INTEL CONFIDENTIAL
 *
 * Copyright 2024 Intel Corporation All Rights Reserved.
 *
 * The source code contained or described herein and all documents related
 * to the source code ("Material") are owned by Intel Corporation or its
 * suppliers or licensors. Title to the Material remains with Intel
 * Corporation or its suppliers and licensors. The Material contains trade
 * secrets and proprietary and confidential information of Intel or its
 * suppliers and licensors. The Material is protected by worldwide copyright
 * and trade secret laws and treaty provisions. No part of the Material
 * may be used, copied, reproduced, modified, published, uploaded, posted,
 * transmitted, distributed, or disclosed in any way without Intel's prior
 * express written permission.
 *
 * No license under any patent, copyright, trade secret or other
 * intellectual property right is granted to or conferred upon you by
 * disclosure or delivery of the Materials, either expressly, by
 * implication, inducement, estoppel or otherwise. Any license under such
 * intellectual property rights must be express and approved by Intel in
 * writing.
 *
 *****************************************************************************/

/**
 * this header file is generated by tool, any direct modification without going
 * through the table generation process will get lost
 */

#ifndef __RF_CALIB_STATIC_DATA_DATA__
#define __RF_CALIB_STATIC_DATA_DATA__

#include "rf_calib_static_data_table.h"

// Initalization related constants for table rf_calib_control_lut
// 1x1x(1x32-bit)
#define RF_CALIB_CONTROL_LUT_DATA \
    {                             \
        [0].value = 0x0           \
    }

// Initalization related constants for table cal_print_config_lut
#define CAL_PRINT_CONFIG_LUT_VALID_ENTRY_NUM (4)
// 1x4x(1x32-bit)
#define CAL_PRINT_CONFIG_LUT_DATA                                                           \
    {                                                                                       \
        [0].value = 0x23ff00, [1].value = 0x23ff00, [2].value = 0xbddd6500, [3].value = 0x0 \
    }

#endif // __RF_CALIB_STATIC_DATA_DATA__
