/* INTEL CONFIDENTIAL
 *
 * Copyright 2024 Intel Corporation All Rights Reserved.
 *
 * The source code contained or described herein and all documents related
 * to the source code ("Material") are owned by Intel Corporation or its
 * suppliers or licensors. Title to the Material remains with Intel
 * Corporation or its suppliers and licensors. The Material contains trade
 * secrets and proprietary and confidential information of Intel or its
 * suppliers and licensors. The Material is protected by worldwide copyright
 * and trade secret laws and treaty provisions. No part of the Material
 * may be used, copied, reproduced, modified, published, uploaded, posted,
 * transmitted, distributed, or disclosed in any way without Intel's prior
 * express written permission.
 *
 * No license under any patent, copyright, trade secret or other
 * intellectual property right is granted to or conferred upon you by
 * disclosure or delivery of the Materials, either expressly, by
 * implication, inducement, estoppel or otherwise. Any license under such
 * intellectual property rights must be express and approved by Intel in
 * writing.
 *
 *****************************************************************************/

/**
 * this header file is generated by tool, any direct modification without going
 * through the table generation process will get lost
 */

#ifndef __RX_STATIC_DATA_CONST__
#define __RX_STATIC_DATA_CONST__

// Table size definition for 1D table: rx_hwa_ant_meta_mapping_lut[8]
#define RX_HWA_ANT_META_MAPPING_LUT_MAX_ENTRY_NUM (8)

// Table size definition for 1D table: rx_print_config_lut[4]
#define RX_PRINT_CONFIG_LUT_MAX_ENTRY_NUM (4)

// Table size definition for 2D table: rx_vha_if_wm_lut[2][4]
#define RX_VHA_IF_WM_LUT_SUB_TBL_NUM   (2)
#define RX_VHA_IF_WM_LUT_MAX_ENTRY_NUM (4)

// Table size definition for 1D table: rx_gain_lut[1]
#define RX_GAIN_LUT_MAX_ENTRY_NUM (1)

// Table size definition for 1D table: rx_topology_lut[5]
#define RX_TOPOLOGY_LUT_MAX_ENTRY_NUM (5)

// Table size definition for 2D table: rx_to_adc_cpu_config_lut[2][8]
#define RX_TO_ADC_CPU_CONFIG_LUT_SUB_TBL_NUM   (2)
#define RX_TO_ADC_CPU_CONFIG_LUT_MAX_ENTRY_NUM (8)

// Table size definition for 1D table: rx_to_adc_cpu_delay_lut[1]
#define RX_TO_ADC_CPU_DELAY_LUT_MAX_ENTRY_NUM (1)

#endif // __RX_STATIC_DATA_CONST__
