/* INTEL CONFIDENTIAL
 *
 * Copyright 2024 Intel Corporation All Rights Reserved.
 *
 * The source code contained or described herein and all documents related
 * to the source code ("Material") are owned by Intel Corporation or its
 * suppliers or licensors. Title to the Material remains with Intel
 * Corporation or its suppliers and licensors. The Material contains trade
 * secrets and proprietary and confidential information of Intel or its
 * suppliers and licensors. The Material is protected by worldwide copyright
 * and trade secret laws and treaty provisions. No part of the Material
 * may be used, copied, reproduced, modified, published, uploaded, posted,
 * transmitted, distributed, or disclosed in any way without Intel's prior
 * express written permission.
 *
 * No license under any patent, copyright, trade secret or other
 * intellectual property right is granted to or conferred upon you by
 * disclosure or delivery of the Materials, either expressly, by
 * implication, inducement, estoppel or otherwise. Any license under such
 * intellectual property rights must be express and approved by Intel in
 * writing.
 *
 *****************************************************************************/

/**
 * this header file is generated by tool, any direct modification without going
 * through the table generation process will get lost
 */

#ifndef __RX_STATIC_DATA_DATA__
#define __RX_STATIC_DATA_DATA__

#include "rx_static_data_table.h"

// Initalization related constants for table rx_hwa_ant_meta_mapping_lut
#define RX_HWA_ANT_META_MAPPING_LUT_VALID_ENTRY_NUM (8)
// 1x8x(1x8-bit)
#define RX_HWA_ANT_META_MAPPING_LUT_DATA                                                                                          \
    {                                                                                                                             \
        [0].value = 0x1, [1].value = 0x2, [2].value = 0x4, [3].value = 0x8, [4].value = 0x10, [5].value = 0x20, [6].value = 0x40, \
        [7].value = 0x80                                                                                                          \
    }

// Initalization related constants for table rx_print_config_lut
#define RX_PRINT_CONFIG_LUT_VALID_ENTRY_NUM (4)
// 1x4x(1x32-bit)
#define RX_PRINT_CONFIG_LUT_DATA                                                            \
    {                                                                                       \
        [0].value = 0x23fd00, [1].value = 0x23fd00, [2].value = 0xbddd6300, [3].value = 0x0 \
    }

// Initalization related constants for table rx_vha_if_wm_lut
#define RX_VHA_IF_WM_F_983MHZ                  (0)
#define RX_VHA_IF_WM_F_983MHZ_VALID_ENTRY_NUM  (4)
#define RX_VHA_IF_WM_F_1474MHZ                 (1)
#define RX_VHA_IF_WM_F_1474MHZ_VALID_ENTRY_NUM (4)
// 2x4x(1x32-bit)
#define RX_VHA_IF_WM_LUT_DATA                                                                                        \
    {                                                                                                                \
        [RX_VHA_IF_WM_F_983MHZ] = {[0].value = 0x2020, [1].value = 0x4040, [2].value = 0x8080, [3].value = 0x10100}, \
        [RX_VHA_IF_WM_F_1474MHZ] = {                                                                                 \
            [0].value = 0x3030,                                                                                      \
            [1].value = 0x6060,                                                                                      \
            [2].value = 0xc0c0,                                                                                      \
            [3].value = 0x18180                                                                                      \
        }                                                                                                            \
    }

// Initalization related constants for table rx_gain_lut
// 1x1x(1x32-bit)
#define RX_GAIN_LUT_DATA    \
    {                       \
        [0].value = 0x15a82 \
    }

// Initalization related constants for table rx_topology_lut
#define RX_TOPOLOGY_SEL_VALID_ENTRY_NUM (5)
// 1x5x(1x8-bit)
#define RX_TOPOLOGY_LUT_DATA                                                                \
    {                                                                                       \
        [0].value = 0x0, [1].value = 0x4, [2].value = 0x2, [3].value = 0x3, [4].value = 0x7 \
    }

// Initalization related constants for table rx_to_adc_cpu_config_lut
#define BSG_WGT_CAL                             (0)
#define BSG_WGT_CAL_VALID_ENTRY_NUM             (8)
#define BSG_SAR_LUT_CALCULATION                 (1)
#define BSG_SAR_LUT_CALCULATION_VALID_ENTRY_NUM (8)
// 2x8x(3x32-bit)
#define RX_TO_ADC_CPU_CONFIG_LUT_DATA                                                                                             \
    {                                                                                                                             \
        [BSG_WGT_CAL] =                                                                                                           \
            {[0].value = {0x0, 0x0, 0x0}, [1].value = {0x0, 0x0, 0x0}, [2].value = {0x0, 0x0, 0x0}, [3].value = {0x0, 0x0, 0x0},  \
             [4].value = {0x0, 0x0, 0x0}, [5].value = {0x0, 0x0, 0x0}, [6].value = {0x0, 0x0, 0x0}, [7].value = {0x0, 0x0, 0x0}}, \
        [BSG_SAR_LUT_CALCULATION] = {                                                                                             \
            [0].value = {0x0, 0x0, 0x0},                                                                                          \
            [1].value = {0x0, 0x0, 0x0},                                                                                          \
            [2].value = {0x0, 0x0, 0x0},                                                                                          \
            [3].value = {0x0, 0x0, 0x0},                                                                                          \
            [4].value = {0x0, 0x0, 0x0},                                                                                          \
            [5].value = {0x0, 0x0, 0x0},                                                                                          \
            [6].value = {0x0, 0x0, 0x0},                                                                                          \
            [7].value = {0x0, 0x0, 0x0}                                                                                           \
        }                                                                                                                         \
    }

// Initalization related constants for table rx_to_adc_cpu_delay_lut
// 1x1x(3x32-bit)
#define RX_TO_ADC_CPU_DELAY_LUT_DATA  \
    {                                 \
        [0].value = { 0x0, 0x0, 0x0 } \
    }

#endif // __RX_STATIC_DATA_DATA__
