/* INTEL CONFIDENTIAL
 *
 * Copyright 2024 Intel Corporation All Rights Reserved.
 *
 * The source code contained or described herein and all documents related
 * to the source code ("Material") are owned by Intel Corporation or its
 * suppliers or licensors. Title to the Material remains with Intel
 * Corporation or its suppliers and licensors. The Material contains trade
 * secrets and proprietary and confidential information of Intel or its
 * suppliers and licensors. The Material is protected by worldwide copyright
 * and trade secret laws and treaty provisions. No part of the Material
 * may be used, copied, reproduced, modified, published, uploaded, posted,
 * transmitted, distributed, or disclosed in any way without Intel's prior
 * express written permission.
 *
 * No license under any patent, copyright, trade secret or other
 * intellectual property right is granted to or conferred upon you by
 * disclosure or delivery of the Materials, either expressly, by
 * implication, inducement, estoppel or otherwise. Any license under such
 * intellectual property rights must be express and approved by Intel in
 * writing.
 *
 *****************************************************************************/

/**
 * this header file is generated by tool, any direct modification without going
 * through the table generation process will get lost
 */

#ifndef __TX_STATIC_DATA_CONST__
#define __TX_STATIC_DATA_CONST__

// Table size definition for 1D table: tx_jesd_ant_meta_mapping_lut[16]
#define TX_JESD_ANT_META_MAPPING_LUT_MAX_ENTRY_NUM (16)

// Table size definition for 1D table: tx_print_config_lut[4]
#define TX_PRINT_CONFIG_LUT_MAX_ENTRY_NUM (4)

// Table size definition for 1D table: tx_dac_conf_lut[12]
#define TX_DAC_CONF_LUT_MAX_ENTRY_NUM (12)

// Table size definition for 1D table: tx_pdpd_mod_lut[8]
#define TX_PDPD_MOD_LUT_MAX_ENTRY_NUM (8)

// Table size definition for 2D table: tx_v2d_if_params_lut[4][7]
#define TX_V2D_IF_PARAMS_LUT_SUB_TBL_NUM   (4)
#define TX_V2D_IF_PARAMS_LUT_MAX_ENTRY_NUM (7)

// Table size definition for 1D table: tx_topology_lut[5]
#define TX_TOPOLOGY_LUT_MAX_ENTRY_NUM (5)

// Table size definition for 2D table: tx_pdpd_pc_sel_lut[3][6]
#define TX_PDPD_PC_SEL_LUT_SUB_TBL_NUM   (3)
#define TX_PDPD_PC_SEL_LUT_MAX_ENTRY_NUM (6)

// Table size definition for 1D table: tx_pdpd_cfg_lut[1]
#define TX_PDPD_CFG_LUT_MAX_ENTRY_NUM (1)

// Table size definition for 1D table: tx_v2d_start_dly_lut[1]
#define TX_V2D_START_DLY_LUT_MAX_ENTRY_NUM (1)

// Table size definition for 1D table: tx_pdpd_dly_lut[1]
#define TX_PDPD_DLY_LUT_MAX_ENTRY_NUM (1)

#endif // __TX_STATIC_DATA_CONST__
