/* INTEL CONFIDENTIAL
 *
 * Copyright 2024 Intel Corporation All Rights Reserved.
 *
 * The source code contained or described herein and all documents related
 * to the source code ("Material") are owned by Intel Corporation or its
 * suppliers or licensors. Title to the Material remains with Intel
 * Corporation or its suppliers and licensors. The Material contains trade
 * secrets and proprietary and confidential information of Intel or its
 * suppliers and licensors. The Material is protected by worldwide copyright
 * and trade secret laws and treaty provisions. No part of the Material
 * may be used, copied, reproduced, modified, published, uploaded, posted,
 * transmitted, distributed, or disclosed in any way without Intel's prior
 * express written permission.
 *
 * No license under any patent, copyright, trade secret or other
 * intellectual property right is granted to or conferred upon you by
 * disclosure or delivery of the Materials, either expressly, by
 * implication, inducement, estoppel or otherwise. Any license under such
 * intellectual property rights must be express and approved by Intel in
 * writing.
 *
 *****************************************************************************/

/**
 * this header file is generated by tool, any direct modification without going
 * through the table generation process will get lost
 */

#ifndef __TX_STATIC_DATA_DATA__
#define __TX_STATIC_DATA_DATA__

#include "tx_static_data_table.h"

// Initalization related constants for table tx_jesd_ant_meta_mapping_lut
#define TX_JESD_ANT_META_MAPPING_LUT_VALID_ENTRY_NUM (16)
// 1x16x(1x32-bit)
#define TX_JESD_ANT_META_MAPPING_LUT_DATA                                                                                         \
    {                                                                                                                             \
        [0].value = 0x1, [1].value = 0x2, [2].value = 0x4, [3].value = 0x8, [4].value = 0x10, [5].value = 0x20, [6].value = 0x40, \
        [7].value = 0x80, [8].value = 0x100, [9].value = 0x209, [10].value = 0x400, [11].value = 0x800, [12].value = 0x1000,      \
        [13].value = 0x2000, [14].value = 0x4002, [15].value = 0x8000                                                             \
    }

// Initalization related constants for table tx_print_config_lut
#define TX_PRINT_CONFIG_LUT_VALID_ENTRY_NUM (4)
// 1x4x(1x32-bit)
#define TX_PRINT_CONFIG_LUT_DATA                                                            \
    {                                                                                       \
        [0].value = 0x23fe00, [1].value = 0x23fe00, [2].value = 0xbddd6400, [3].value = 0x0 \
    }

// Initalization related constants for table tx_dac_conf_lut
#define DAC_CONF_VALID_ENTRY_NUM (12)
// 1x12x(1x32-bit)
#define TX_DAC_CONF_LUT_DATA                                                                                                         \
    {                                                                                                                                \
        [0].value = 0x21c0, [1].value = 0x1240a, [2].value = 0x1488c, [3].value = 0x4421, [4].value = 0x148ab, [5].value = 0x148ad,  \
        [6].value = 0x21c0, [7].value = 0x1240a, [8].value = 0x1488c, [9].value = 0x21f1, [10].value = 0x1243b, [11].value = 0x124bd \
    }

// Initalization related constants for table tx_pdpd_mod_lut
#define PDPD_MOD_SEL_VALID_ENTRY_NUM (8)
// 1x8x(1x16-bit)
#define TX_PDPD_MOD_LUT_DATA                                                                                                    \
    {                                                                                                                           \
        [0].value = 0x2680, [1].value = 0x4812, [2].value = 0x71d2, [3].value = 0x4813, [4].value = 0x71d3, [5].value = 0xf09e, \
        [6].value = 0xf09f, [7].value = 0x23a0                                                                                  \
    }

// Initalization related constants for table tx_v2d_if_params_lut
#define V2D_AC_BUF0_LUT                 (0)
#define V2D_AC_BUF0_LUT_VALID_ENTRY_NUM (7)
#define V2D_B_BUF0_LUT                  (1)
#define V2D_B_BUF0_LUT_VALID_ENTRY_NUM  (7)
#define V2D_AC_BUF1_LUT                 (2)
#define V2D_AC_BUF1_LUT_VALID_ENTRY_NUM (7)
#define V2D_B_BUF1_LUT                  (3)
#define V2D_B_BUF1_LUT_VALID_ENTRY_NUM  (7)
// 4x7x(1x32-bit)
#define TX_V2D_IF_PARAMS_LUT_DATA                                                                                      \
    {                                                                                                                  \
        [V2D_AC_BUF0_LUT] = {[0].value = 0x3ff800,  [1].value = 0x1ff800,  [2].value = 0x17ffc00, [3].value = 0xff800, \
                             [4].value = 0x15ffa00, [5].value = 0x2affc00, [6].value = 0x3fffe00},                     \
        [V2D_B_BUF0_LUT] = {[0].value = 0x3ff800,  [1].value = 0x1ff800,  [2].value = 0x17ffc00, [3].value = 0xff800,  \
                            [4].value = 0x15ffa00, [5].value = 0x2affc00, [6].value = 0x3fffe00},                      \
        [V2D_AC_BUF1_LUT] = {[0].value = 0x1ff800,  [1].value = 0xff800,   [2].value = 0x15ffa00, [3].value = 0x7f800, \
                             [4].value = 0x14ff900, [5].value = 0x297fa00, [6].value = 0x3dffb00},                     \
        [V2D_B_BUF1_LUT] = {                                                                                           \
            [0].value = 0x3ffc00,                                                                                      \
            [1].value = 0x2ffc00,                                                                                      \
            [2].value = 0x17ffe00,                                                                                     \
            [3].value = 0x27fc00,                                                                                      \
            [4].value = 0x16ffd00,                                                                                     \
            [5].value = 0x2b7fe00,                                                                                     \
            [6].value = 0x3ffff00                                                                                      \
        }                                                                                                              \
    }

// Initalization related constants for table tx_topology_lut
#define TX_TOPOLOGY_SEL_VALID_ENTRY_NUM (5)
// 1x5x(1x8-bit)
#define TX_TOPOLOGY_LUT_DATA                                                                \
    {                                                                                       \
        [0].value = 0x0, [1].value = 0x4, [2].value = 0x2, [3].value = 0x3, [4].value = 0x7 \
    }

// Initalization related constants for table tx_pdpd_pc_sel_lut
#define PDPD_OP_MOD_NORM                 (0)
#define PDPD_OP_MOD_NORM_VALID_ENTRY_NUM (5)
#define PDPD_OP_MOD_LP                   (1)
#define PDPD_OP_MOD_LP_VALID_ENTRY_NUM   (6)
#define PDPD_OP_MOD_ELP                  (2)
#define PDPD_OP_MOD_ELP_VALID_ENTRY_NUM  (6)
// 3x6x(1x8-bit)
#define TX_PDPD_PC_SEL_LUT_DATA                                                                                                         \
    {                                                                                                                                   \
        [PDPD_OP_MOD_NORM] = {[0].value = 0x0, [1].value = 0x9, [2].value = 0x12, [3].value = 0x5b, [4].value = 0xa4},                  \
        [PDPD_OP_MOD_LP] = {[0].value = 0xa, [1].value = 0x53, [2].value = 0x4b, [3].value = 0x9c, [4].value = 0x94, [5].value = 0x8c}, \
        [PDPD_OP_MOD_ELP] = {                                                                                                           \
            [0].value = 0xa,                                                                                                            \
            [1].value = 0x13,                                                                                                           \
            [2].value = 0xb,                                                                                                            \
            [3].value = 0x5c,                                                                                                           \
            [4].value = 0x14,                                                                                                           \
            [5].value = 0xc                                                                                                             \
        }                                                                                                                               \
    }

// Initalization related constants for table tx_pdpd_cfg_lut
// 1x1x(1x8-bit)
#define TX_PDPD_CFG_LUT_DATA \
    {                        \
        [0].value = 0xff     \
    }

// Initalization related constants for table tx_v2d_start_dly_lut
// 1x1x(3x32-bit)
#define TX_V2D_START_DLY_LUT_DATA        \
    {                                    \
        [0].value = { 0x1100, 0x0, 0x0 } \
    }

// Initalization related constants for table tx_pdpd_dly_lut
// 1x1x(1x16-bit)
#define TX_PDPD_DLY_LUT_DATA \
    {                        \
        [0].value = 0x0      \
    }

#endif // __TX_STATIC_DATA_DATA__
