{STRM2CIO_INT_EN_ADR(VEXABC0_S2C_STRM2CIO_BASE), 0xF, 0xFFFFFFFF, "STRM2CIO_INT_ENABLE"},
{STRM2CIO_FIFO_STAT_CTL_ADR(VEXABC0_S2C_STRM2CIO_BASE), 0x1, 0xFFFFFFFF, "STRM2CIO_MEM_FIFO_STATUS_CTL"},
{STRM2CIO_WORD_CNT_CTL_ADR(VEXABC0_S2C_STRM2CIO_BASE), 0x1, 0xFFFFFFFF, "STRM2CIO_MEM_WORD_CNT_CTL"},
